import { Router, type IRouter } from "express";
import healthRouter from "./health";
import processesRouter from "./processes";
import anthropicRouter from "./anthropic";
import auditLogsRouter from "./audit-logs";
import governanceRouter from "./governance";
import aiAgentsRouter from "./ai-agents";
import workflowsRouter from "./workflows";
import checklistsRouter from "./checklists";
import { usersRouter } from "./users";
import { orgRouter } from "./org";
import { initiativesRouter } from "./initiatives";
import { reportsRouter } from "./reports";
import { dashboardsRouter } from "./dashboards";
import { authRouter } from "./auth";
import { blueprintRouter } from "./blueprint";
import { creditsRouter } from "./credits";
import { formsRouter } from "./forms";
import knowledgeRouter from "./knowledge";
import activitiesRouter from "./activities";
import processAttachmentsRouter from "./process-attachments";
import tasksRouter from "./tasks";
import connectorConfigsRouter from "./connector-configs";
import { strategyRouter } from "./strategy";
import { favouritesRouter } from "./favourites";

const router: IRouter = Router();

router.use('/auth', authRouter);
router.use(blueprintRouter);
router.use(healthRouter);
router.use(governanceRouter);
router.use(processesRouter);
router.use(anthropicRouter);
router.use(auditLogsRouter);
router.use(aiAgentsRouter);
router.use(workflowsRouter);
router.use(checklistsRouter);
router.use('/users', usersRouter);
router.use(orgRouter);
router.use(initiativesRouter);
router.use(reportsRouter);
router.use(dashboardsRouter);
router.use(creditsRouter);
router.use(formsRouter);
router.use(knowledgeRouter);
router.use(activitiesRouter);
router.use(processAttachmentsRouter);
router.use(tasksRouter);
router.use(connectorConfigsRouter);
router.use(strategyRouter);
router.use(favouritesRouter);

export default router;
