/**
 * One-time seed script: sets industry_benchmark, priority, and bpmn
 * for all 100 nonprofit processes.
 *
 * Run with:
 *   cd <repo-root>
 *   DATABASE_URL="postgresql://postgres@127.0.0.1/businessos" pnpm tsx scripts/seed-process-data.ts
 */

import pg from "pg";

const { Pool } = pg;

const pool = new Pool({
  connectionString:
    process.env.DATABASE_URL ?? "postgresql://postgres@127.0.0.1/businessos",
});

// ── BPMN template ─────────────────────────────────────────────────────────────

function bpmn(
  processId: string,
  processName: string,
  tasks: [string, string, string, string],
): string {
  const safe = (s: string) =>
    s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
  const [t1, t2, t3, t4] = tasks.map(safe);
  const pn = safe(processName);
  const pid = processId.replace(/[^a-zA-Z0-9_]/g, "_");

  return `<?xml version="1.0" encoding="UTF-8"?>
<bpmn:definitions xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" targetNamespace="http://bpmn.io/schema/bpmn" id="Def_${pid}">
  <bpmn:process id="Proc_${pid}" name="${pn}" isExecutable="false">
    <bpmn:startEvent id="SE_1" name="Start"><bpmn:outgoing>F1</bpmn:outgoing></bpmn:startEvent>
    <bpmn:task id="T1" name="${t1}"><bpmn:incoming>F1</bpmn:incoming><bpmn:outgoing>F2</bpmn:outgoing></bpmn:task>
    <bpmn:task id="T2" name="${t2}"><bpmn:incoming>F2</bpmn:incoming><bpmn:outgoing>F3</bpmn:outgoing></bpmn:task>
    <bpmn:task id="T3" name="${t3}"><bpmn:incoming>F3</bpmn:incoming><bpmn:outgoing>F4</bpmn:outgoing></bpmn:task>
    <bpmn:task id="T4" name="${t4}"><bpmn:incoming>F4</bpmn:incoming><bpmn:outgoing>F5</bpmn:outgoing></bpmn:task>
    <bpmn:endEvent id="EE_1" name="End"><bpmn:incoming>F5</bpmn:incoming></bpmn:endEvent>
    <bpmn:sequenceFlow id="F1" sourceRef="SE_1" targetRef="T1"/>
    <bpmn:sequenceFlow id="F2" sourceRef="T1" targetRef="T2"/>
    <bpmn:sequenceFlow id="F3" sourceRef="T2" targetRef="T3"/>
    <bpmn:sequenceFlow id="F4" sourceRef="T3" targetRef="T4"/>
    <bpmn:sequenceFlow id="F5" sourceRef="T4" targetRef="EE_1"/>
  </bpmn:process>
  <bpmndi:BPMNDiagram id="Diagram_1">
    <bpmndi:BPMNPlane id="Plane_1" bpmnElement="Proc_${pid}">
      <bpmndi:BPMNShape id="SE_1_di" bpmnElement="SE_1"><dc:Bounds x="152" y="82" width="36" height="36"/><bpmndi:BPMNLabel><dc:Bounds x="155" y="125" width="30" height="14"/></bpmndi:BPMNLabel></bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="T1_di" bpmnElement="T1"><dc:Bounds x="240" y="60" width="140" height="80"/></bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="T2_di" bpmnElement="T2"><dc:Bounds x="430" y="60" width="140" height="80"/></bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="T3_di" bpmnElement="T3"><dc:Bounds x="620" y="60" width="140" height="80"/></bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="T4_di" bpmnElement="T4"><dc:Bounds x="810" y="60" width="140" height="80"/></bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="EE_1_di" bpmnElement="EE_1"><dc:Bounds x="1002" y="82" width="36" height="36"/><bpmndi:BPMNLabel><dc:Bounds x="1006" y="125" width="28" height="14"/></bpmndi:BPMNLabel></bpmndi:BPMNShape>
      <bpmndi:BPMNEdge id="F1_di" bpmnElement="F1"><di:waypoint x="188" y="100"/><di:waypoint x="240" y="100"/></bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="F2_di" bpmnElement="F2"><di:waypoint x="380" y="100"/><di:waypoint x="430" y="100"/></bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="F3_di" bpmnElement="F3"><di:waypoint x="570" y="100"/><di:waypoint x="620" y="100"/></bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="F4_di" bpmnElement="F4"><di:waypoint x="760" y="100"/><di:waypoint x="810" y="100"/></bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="F5_di" bpmnElement="F5"><di:waypoint x="950" y="100"/><di:waypoint x="1002" y="100"/></bpmndi:BPMNEdge>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</bpmn:definitions>`;
}

// ── Process data: [id, processName, [4 task names], industryBenchmark, priority] ──

type ProcessRow = [number, string, [string, string, string, string], string, number];

const DATA: ProcessRow[] = [
  // ── Strategy & Governance ─────────────────────────────────────────────────
  [1,  "Multi-Year Strategy Planning",     ["Gather strategic intelligence & stakeholder input", "Draft multi-year strategic plan", "Board review & approval", "Cascade to programs & track alignment"],    "Top-quartile nonprofits review strategy every 3–5 years; 70%+ of programs aligned to strategic plan; sector-leading organisations refresh annually",  1],
  [2,  "Annual Budget Allocation",         ["Collect departmental bids & revenue forecasts", "Finance team consolidation & scenario modelling", "Leadership review & challenge session", "Board approval & allocation communication"],    "Best practice: <5% budget variance; programme spend >65% of total budget; admin cost ratio <15%; monthly reforecast",  1],
  [3,  "Board Meeting Preparation",        ["Compile papers & management reports", "Quality review & sign-off by CEO", "Distribute board pack to trustees", "Capture decisions & action log post-meeting"],    "Best practice: board packs distributed 5 working days in advance; quorum achieved at 95%+ of meetings; minutes circulated within 5 days",  2],
  [4,  "Outcomes Framework Design",        ["Map programme theory of change", "Define measurable indicators & data sources", "Stakeholder co-design & validation", "Embed into reporting & programme delivery"],    "Leading nonprofits: 100% of programmes with logic model; measurable outcomes for 80%+ of activities; reviewed annually with beneficiaries",  2],
  [5,  "Enterprise Risk Register",         ["Identify & assess risks across the organisation", "Score likelihood & impact; assign owners", "Develop & implement mitigation actions", "Report to board & update register quarterly"],    "Best practice: quarterly risk review cycle; all high risks have named owners; critical risk mitigations actioned within 30 days",  1],
  [6,  "Stakeholder Trust Survey",         ["Design survey & define stakeholder cohorts", "Distribute & collect responses", "Analyse results & benchmark against prior year", "Report findings & implement improvement actions"],    "Sector NPS benchmark: +20 to +40; 70%+ response rate from key stakeholders; annual cadence minimum; top performers bi-annual",  3],
  [7,  "Quarterly KPI Review",             ["Collect actuals from department heads", "Validate data & prepare performance dashboard", "Leadership review & root-cause analysis", "Agree actions & communicate to board"],    "Best practice: 85%+ KPI attainment rate; review completed within 5 working days of quarter-end; all red KPIs have recovery plans",  2],
  [8,  "Peer Impact Benchmarking",         ["Identify peer organisations & benchmarking frameworks", "Gather comparative data & normalise metrics", "Analyse performance gaps & opportunities", "Present insights to leadership & set stretch targets"],    "Top-quartile nonprofits participate in 2+ peer benchmarking initiatives annually; use ACEVO/NPC frameworks; 80%+ metrics benchmarked",  4],
  [9,  "Theory of Change Review",          ["Review current ToC against programme evidence", "Conduct stakeholder consultations & beneficiary feedback", "Update logic model & assumptions", "Communicate revised ToC to staff, funders & board"],    "Best practice: ToC reviewed annually with beneficiary input; 85%+ stakeholder clarity score; assumptions tested against evidence base",  2],
  [10, "Cause Area Assessment",            ["Scan emerging cause areas & funding landscape", "Conduct desk research & expert interviews", "Score areas against mission alignment & feasibility", "Present recommendations to leadership for decision"],    "Leading nonprofits formally assess 3–5 new opportunity areas per year; expansion success rate >60% within 3 years of entry",  3],

  // ── Fundraising & Donor Management ────────────────────────────────────────
  [11, "Major Donor Prospecting",          ["Research & qualify major donor prospects", "Score & prioritise pipeline against wealth & affinity", "Assign relationship managers & draft engagement plans", "Track cultivation progress & update CRM"],    "Sector average prospect-to-donor conversion: 10–15%; top performers: 20–30%; cost per prospect identified <£50; pipeline value tracked monthly",  1],
  [12, "Donor Cultivation Proposals",      ["Research donor interests & giving history", "Draft personalised proposal & impact narrative", "Internal review & CEO/Chair sign-off", "Submit proposal & follow up within 5 days"],    "Best practice: proposal acceptance rate 25–40%; first response within 48 hours; average 1.5 revision cycles before final submission",  1],
  [13, "Donor Campaign Segmentation",      ["Export & clean CRM donor data", "Apply RFM segmentation model", "Design tailored messaging per segment", "Execute campaign & track response rates by segment"],    "Average response rate: 5–10% cold; 20–35% warm; cost per £ raised <£0.25 for direct mail; email campaigns target 3–5% CTR",  2],
  [14, "Donor Stewardship Automation",     ["Design stewardship journey & touchpoint schedule", "Configure automation rules in CRM", "Test journeys & validate communications", "Monitor engagement metrics & optimise triggers"],    "Best practice: acknowledgement within 24 hours of gift; 4–6 stewardship touches per major donor per year; automated stewardship improves retention by 10–15%",  1],
  [15, "Donor Churn Prevention",           ["Identify lapsed & at-risk donors via CRM analytics", "Segment by lapse period & giving history", "Execute targeted reactivation campaign", "Track reactivation rate & update suppression lists"],    "Sector average donor retention: 45%; top performers: 65–70%; first-year retention benchmark: 25–30%; lapsed reactivation rate 8–15%",  1],
  [16, "Fundraising Revenue Forecast",     ["Collect pipeline data from fundraising teams", "Build rolling 12-month forecast by income stream", "Scenario model best/base/worst case", "Present to CFO & adjust plans accordingly"],    "Best practice: forecast accuracy within ±10% of actual; monthly rolling forecast update; scenario planning for all income streams >10% of total",  2],
  [17, "Fundraising Event Logistics",      ["Define event concept, budget & KPIs", "Coordinate venue, suppliers & speakers", "Execute event & manage guest experience", "Reconcile financials & capture follow-up actions"],    "Sector benchmark: event ROI 2:1 to 4:1; net revenue per attendee £50–£200; post-event donor upgrade rate 5–10% within 6 months",  3],
  [18, "P2P Campaign Monitoring",          ["Launch P2P platform & recruit fundraisers", "Monitor activation & send coaching communications", "Track revenue against milestones in real time", "Reconcile funds & thank top fundraisers"],    "Sector average: £500–£1,000 raised per active fundraiser; 30–40% of registered fundraisers active; average gift size on P2P platforms £25–£50",  3],
  [19, "Fundraising Platform Integration", ["Map data fields between CRM & fundraising platforms", "Configure API or file-based integration", "Test data flows & validate matching logic", "Monitor sync logs & resolve exceptions"],    "Best practice: <1% duplicate rate; same-day data sync; 98%+ data match rate; integration health checked daily",  2],
  [20, "Gift Acceptance Policy",           ["Review gift against policy criteria & due diligence", "Escalate complex gifts to Gift Acceptance Committee", "Issue formal acknowledgement & gift agreement", "Record in CRM & notify Finance for processing"],    "Best practice: policy reviewed annually; 100% of restricted gifts acknowledged within 48 hours; gift rejection rate <2%; recognition accuracy 100%",  3],

  // ── Grant Management ───────────────────────────────────────────────────────
  [21, "Grant Opportunity Scanning",       ["Monitor funder portals, alerts & intelligence sources", "Score opportunities against mission & eligibility criteria", "Triage shortlist with fundraising & programme leads", "Log eligible opportunities in grants pipeline system"],    "Top performers review 50+ opportunities per year; submit to 70%+ of eligible grants; opportunity-to-application conversion rate tracked monthly",  2],
  [22, "Grant Application Writing",        ["Brief programme team & gather evidence base", "Draft application narrative & budget", "Internal review & compliance check", "Submit & confirm receipt; log in grants system"],    "Sector average success rate: 20–35%; top performers: 40–60%; application turnaround <10 working days; revision cycles <2",  1],
  [23, "Grant Compliance Calendar",        ["Extract all compliance obligations from grant agreements", "Build and share compliance calendar with owners", "Send automated 30-day advance alerts for deadlines", "Track completion & escalate overdue obligations"],    "Best practice: 100% on-time reporting; 30-day advance alert for all obligations; zero missed deadlines in top-performing organisations",  1],
  [24, "Grant Progress Reporting",         ["Collect programme data & financial expenditure reports", "Draft narrative progress report against grant milestones", "Finance & programme director review & sign-off", "Submit to funder & log acceptance confirmation"],    "Best practice: first-submission acceptance rate >90%; average 1.2 revision cycles; preparation time <3 working days for standard reports",  1],
  [25, "Grant Budget Monitoring",          ["Download expenditure actuals from finance system", "Compare actuals to grant budget & flag variances >5%", "Discuss variances with programme & finance teams", "Prepare budget reforecast & seek funder approval if needed"],    "Best practice: budget variance <5%; underspend <10% at mid-point; grant close-out completed within 60 days of end date",  2],
  [26, "Funder Relationship Management",   ["Prepare for annual funder review meeting", "Conduct meeting & present impact evidence", "Record key messages & agreed actions in CRM", "Follow up with thank-you & next steps within 5 days"],    "Best practice: annual funder review meetings for all funders >£25k; follow-on grant conversion rate 60%+; relationship health score tracked quarterly",  2],
  [27, "Consortium Grant Reporting",       ["Issue data collection templates to consortium partners", "Validate & consolidate partner submissions", "Draft consolidated narrative & financial report", "Circulate to lead partner for sign-off & submit to funder"],    "Best practice: consolidated report within 10 days of data collection close; partner data quality >95%; lead partner review within 3 days",  3],
  [28, "Sub-Grantee Proposal Review",      ["Circulate call for proposals to eligible sub-grantees", "Conduct structured scoring using published criteria", "Moderation panel review & award decision", "Notify applicants & issue grant agreements"],    "Best practice: scoring panel of 3+ reviewers; inter-rater reliability >80%; award decision within 30 days of deadline; 100% applicants notified",  3],
  [29, "Grants System Data Quality",       ["Run monthly data quality audit against defined rules", "Generate exception report & assign corrections", "Update records & validate completeness", "Produce data quality score dashboard for management"],    "Best practice: 95%+ data accuracy; 100% audit-ready records; system updated within 5 working days of grant event; zero orphaned records",  2],
  [30, "Funder Intelligence Database",     ["Schedule quarterly funder database review", "Research updated funder priorities & giving statistics", "Update database records & enrich with new funders", "Share funder intelligence digest with fundraising team"],    "Best practice: 80%+ of records updated within 12 months; cover all funders with >£50k giving potential in target geography",  3],

  // ── Marketing, Brand & Communications ─────────────────────────────────────
  [31, "Content Calendar Planning",        ["Gather content inputs from all teams & campaigns", "Draft 4-week rolling content calendar", "Cross-team review & channel alignment", "Publish calendar & brief content creators"],    "Best practice: 4-week advance planning cycle; 85%+ calendar adherence; cross-channel message alignment; content engagement benchmarked monthly",  2],
  [32, "Social Media Content Creation",    ["Define content brief & campaign goals", "Create copy, visuals & multimedia assets", "Internal review, approval & accessibility check", "Schedule & publish; monitor engagement within 24 hours"],    "Nonprofit benchmark: 1–3% engagement on Facebook; 3–6% on Instagram; 0.5–1% on LinkedIn; posting frequency 3–5x/week for optimal reach",  3],
  [33, "Donor Email Newsletters",          ["Segment email list & define personalisation rules", "Draft and design newsletter content", "Test across clients & send to approval stakeholder", "Schedule send & monitor open/click metrics within 48 hours"],    "Nonprofit sector: open rate 25–28%; CTR 3–5%; unsubscribe rate <0.5%; list growth 10–20% per year; A/B test every 3rd send",  2],
  [34, "Brand Monitoring",                 ["Set up media & social listening alerts", "Daily review of brand mentions & sentiment", "Respond to queries & escalate issues within 4 hours", "Weekly sentiment report to comms & leadership team"],    "Best practice: response to media queries within 4 hours; daily social sentiment monitoring; track share-of-voice against peer organisations monthly",  2],
  [35, "Impact Report Production",         ["Gather programme data, case studies & financial summary", "Draft narrative & design impact report layout", "Stakeholder review, photography & final approval", "Publish & distribute to donors, funders & board"],    "Best practice: published within 6 months of year-end; 70%+ donor readership within 3 months; report-driven gift uplift tracked",  2],
  [36, "SEO & Digital Advertising",        ["Keyword research & audit of current digital performance", "Set up or optimise Google Grant campaigns & paid ads", "Develop ad copy, landing pages & conversion tracking", "Monitor weekly & optimise bids, copy & audiences"],    "Google for Nonprofits grant: $10k/month; target CPA <£50 for new donors; organic traffic growth 20%+ YoY; ROAS >4:1 for paid campaigns",  3],
  [37, "Communications Localisation",      ["Receive source content & briefing from global team", "Translate & culturally adapt messaging", "Native-speaker review & back-translation check", "Publish localised content & measure regional engagement"],    "Best practice: translation review by native speakers; 2-week localisation cycle; regional engagement uplift 15%+; glossary maintained for key terms",  4],
  [38, "Ambassador Programme Management",  ["Recruit & onboard ambassadors with clear role briefs", "Co-create campaign content & talking points", "Activate ambassadors for campaigns & events", "Track reach, referrals & ambassador-driven donations"],    "Best practice: 20+ active ambassadors; 3–4 campaign activations per year; 5%+ of fundraising revenue attributed to ambassador activity",  3],
  [39, "Audience Sentiment Analysis",      ["Design sentiment data collection methodology", "Administer surveys or social listening analysis", "Analyse sentiment trends & message resonance", "Report findings & brief comms team on optimisation"],    "Best practice: quarterly sentiment tracking; message resonance score >70%; rapid response protocol triggers within 24 hours of sentiment drop",  3],
  [40, "Crisis Communications Planning",   ["Identify crisis scenarios & key risk triggers", "Draft holding statements & spokesperson briefings", "Run scenario training with comms & leadership team", "Activate plan, monitor coverage & brief stakeholders"],    "Best practice: first response within 2 hours; plan tested annually via tabletop exercise; stakeholder trust recovery within 90 days post-crisis",  2],

  // ── Program Delivery & Operations ─────────────────────────────────────────
  [41, "Beneficiary Intake Design",        ["Design intake form & eligibility criteria", "Build intake process & decision workflow", "Pilot with test cohort & gather feedback", "Launch & monitor processing time & accuracy"],    "Best practice: intake processing <5 business days; 95%+ eligibility determination accuracy; applicant experience NPS >60; reviewed annually",  1],
  [42, "Programme Delivery Monitoring",    ["Set programme milestones & assign accountability", "Collect monthly progress data from delivery teams", "Analyse variance & identify risks or issues", "Report to management & agree corrective actions"],    "Leading nonprofits: 85%+ milestone completion rate; issues resolved within 14 days; monthly variance reporting; programme review quarterly",  1],
  [43, "Beneficiary Outcome Analysis",     ["Define outcome indicators & data collection tools", "Collect outcome data at regular intervals", "Analyse results & compare to baseline & theory of change", "Report outcomes to funders, board & internally"],    "Best practice: 90%+ data completeness; 80%+ of programmes with measurable outcomes; quarterly review cycles; results shared publicly annually",  1],
  [44, "Volunteer Scheduling",             ["Publish available shifts & required roles", "Match volunteers to shifts based on skills & availability", "Send confirmations & reminders 48 hours in advance", "Record attendance & capture volunteer feedback"],    "Best practice: 95%+ shift fill rate; no-show rate <5%; volunteer satisfaction score >80%; scheduling system automated where possible",  2],
  [45, "Programme Procurement Management", ["Define procurement need & draft specification", "Source quotes or run competitive tender process", "Evaluate bids & award to preferred supplier", "Manage contract & monitor delivery against SLA"],    "Best practice: competitive tender for all contracts >£10k; procurement cycle <90 days; 10–15% cost savings vs initial budget estimate",  2],
  [46, "Beneficiary Satisfaction Surveys", ["Design survey instrument & determine sample frame", "Distribute survey via preferred channels", "Analyse results & identify themes", "Share insights with programme team & implement improvements"],    "Sector benchmark: 60–70% survey response rate; NPS >40; 80% of improvement recommendations actioned within 90 days",  2],
  [47, "Safeguarding Case Management",     ["Receive & log safeguarding concern within 24 hours", "Conduct initial risk assessment & notify DSL", "Investigate & apply case management protocol", "Close case with documented outcome & lessons learned"],    "Legal requirement: 100% incidents reported within 24 hours; 90-day case closure standard; 100% compliance audit pass rate; DSL trained annually",  1],
  [48, "Field Mission Logistics",          ["Define mission scope, budget & safety protocols", "Coordinate travel, accommodation & equipment", "Brief team & confirm in-country support arrangements", "Execute mission; debrief & capture lessons learned"],    "Best practice: mission preparation completed 5 working days before departure; cost variance <10%; zero preventable safety incidents; debrief within 5 days",  2],
  [49, "Programme Budget Forecasting",     ["Collect actuals from finance & programme teams", "Update rolling 12-month programme budget forecast", "Identify risks & flag variances >5% to management", "Reforecast & seek re-approval if material changes required"],    "Best practice: monthly forecast cycle; variance <5%; budget utilisation 90–95%; grant-level forecasting for restricted funds",  2],
  [50, "Programme Learning Cycles",        ["Define learning questions for the cycle", "Gather evidence from data, staff & beneficiaries", "Analyse findings & generate actionable recommendations", "Share learning & track implementation of recommendations"],    "Best practice: quarterly learning cycles; 75%+ recommendations implemented within 6 months; annual programme improvement evidenced & published",  3],

  // ── Finance & Compliance ───────────────────────────────────────────────────
  [51, "Management Accounts Preparation",  ["Extract trial balance & nominal ledger data", "Prepare management accounts pack with variance commentary", "Finance director review & sign-off", "Submit to board within 10 working days of month-end"],    "Best practice: management accounts within 10 working days of month-end; 100% on-time board delivery; budget variance explained for all lines >5%",  1],
  [52, "Accounts Payable Processing",      ["Receive & validate supplier invoices", "Obtain purchase order match & authorisation", "Process payment run in finance system", "Reconcile AP ledger & resolve outstanding items"],    "Sector benchmark: invoice processing within 5 working days; payment on time >95%; exception rate <2%; supplier statement reconciliation monthly",  2],
  [53, "Statutory Financial Statements",   ["Prepare draft statutory accounts to SORP standard", "External audit fieldwork & response to queries", "Audit sign-off & trustee approval", "File with Companies House & Charity Commission"],    "Best practice: filed at least 2 months before statutory deadline; <5 audit adjustments; 100% disclosure completeness; clean audit opinion",  1],
  [54, "Fund Accounting Reconciliation",   ["Extract fund balances from finance system", "Reconcile restricted & unrestricted fund movements", "Identify & resolve discrepancies with programme team", "Produce reconciled fund statement for management"],    "Best practice: 100% fund reconciliation monthly; zero restricted fund breaches; close within 3 working days of month-end; restrictions monitored in real time",  1],
  [55, "Gift Aid Filing",                  ["Validate donor declarations in CRM against eligibility rules", "Prepare HMRC submission data & reconcile to CRM", "Submit R68/online claim & confirm HMRC receipt", "Reconcile payment received & post to finance system"],    "UK sector: reclaim 25p per £1 eligible donation; submission accuracy 100%; HMRC processing time 4–6 weeks; missed Gift Aid <1% of eligible donations",  2],
  [56, "Internal Audit Reviews",           ["Plan audit scope & risk-based audit programme", "Conduct fieldwork & gather evidence", "Draft findings & recommendations report", "Agree management responses & track remediation to closure"],    "Best practice: 85%+ control effectiveness rating; findings resolved within 90 days; zero repeat findings in consecutive annual audit",  2],
  [57, "Payroll & PAYE Processing",        ["Collect starters, leavers & change notifications", "Process payroll calculations in payroll system", "Submit RTI to HMRC & pay employees", "Reconcile payroll control accounts & file P60s/P11Ds"],    "Best practice: 99.9%+ payroll accuracy; 100% on-time payment; zero PAYE compliance breaches; monthly payroll reconciliation reviewed by Finance Director",  1],
  [58, "Cash Flow Forecasting",            ["Gather income & expenditure forecasts from teams", "Build 13-week rolling cash flow model", "Present to CFO & flag liquidity risks", "Update weekly & compare actuals to forecast"],    "Best practice: 12-week rolling forecast; maintain 3–6 months operating reserves; forecast accuracy ±10%; liquidity risk escalated within 24 hours of trigger",  1],
  [59, "Regulatory Compliance Monitoring", ["Maintain compliance obligations register", "Monitor regulatory changes & deadlines", "Complete required filings & returns on time", "Report compliance status to board & Audit Committee"],    "Best practice: 100% compliance score; zero overdue obligations; zero regulatory breaches; obligations register reviewed quarterly by Finance Director",  1],
  [60, "Expense Claims Processing",        ["Staff submit claims with receipts via expense system", "Line manager approval against policy", "Finance team validate against policy & process payment", "Reconcile expense accounts & flag policy breaches"],    "Best practice: claims processed within 5 working days; 100% policy compliance; exception rate <1%; month-end expense accrual variance <£500",  3],

  // ── HR, Volunteers & Talent ────────────────────────────────────────────────
  [61, "Recruitment & Screening",          ["Agree job description, grade & advertising channels", "Screen applications against essential criteria", "Conduct structured interviews & skills assessments", "Make selection decision, offer & complete pre-employment checks"],    "Sector benchmark: time to shortlist 10–15 days; 30%+ diverse shortlists; quality of hire assessed at 6 months; cost per hire <£2,000 for non-specialist roles",  2],
  [62, "Staff Onboarding Management",      ["Prepare workstation, accounts & welcome pack", "Conduct structured first week induction programme", "Assign buddy & schedule 30/60/90-day check-ins", "Complete probation review & celebrate successful completion"],    "Best practice: 100% onboarding completion within 90 days; time to productivity <3 months; new joiner NPS >70; reduced early attrition rate",  2],
  [63, "Learning & Development Planning",  ["Conduct annual training needs analysis with managers", "Design L&D programme & curate learning resources", "Deliver training & track completion in HRIS", "Evaluate learning impact against skill gap closure"],    "Best practice: 90%+ training completion rate; 2–3% of payroll invested in L&D; 80% of priority skill gaps addressed within 12 months",  3],
  [64, "Performance Review Cycles",        ["Launch review cycle & brief managers", "Staff complete self-assessments; managers prepare feedback", "Conduct 1:1 review conversations & agree goals", "Calibrate ratings & finalise records in HRIS"],    "Best practice: 100% reviews completed on time; goal alignment rate 85%+; biannual review cadence; ratings calibrated across teams for consistency",  2],
  [65, "Employee Wellbeing Monitoring",    ["Administer wellbeing pulse survey quarterly", "Analyse absence trends & EAP utilisation data", "Identify burnout risk flags & brief line managers", "Implement targeted wellbeing interventions & track impact"],    "Sector benchmark: absence rate <3%; EAP utilisation 5–10%; wellbeing score >7/10; burnout flags trigger manager conversation within 5 days",  2],
  [66, "DBS & Safeguarding Checks",        ["Identify roles requiring DBS check level & frequency", "Initiate DBS application via registered body", "Receive disclosure & assess suitability", "Record outcome in HRIS & schedule renewal alert"],    "Legal requirement: 100% DBS completion before start in regulated activity; renewals within 3-year cycle; zero compliance lapses; records retained per statutory guidance",  1],
  [67, "Staff Retention Analysis",         ["Extract turnover data & exit interview themes", "Identify flight-risk cohorts via HRIS analytics", "Brief managers & develop targeted retention interventions", "Track voluntary turnover monthly & report to board annually"],    "Sector average voluntary turnover: 18–22%; top performers: <12%; first-year attrition benchmark: <15%; cost of turnover estimated at 50–200% of salary",  2],
  [68, "Workforce Planning",               ["Analyse current headcount vs strategic plan requirements", "Model workforce scenarios for 1–3 year horizon", "Identify gaps & build hiring/development pipeline", "Review quarterly & adjust plan based on programme changes"],    "Best practice: 12-month workforce plan reviewed quarterly; vacancy fill rate >85%; skills gaps mapped annually; succession planning for all senior roles",  2],
  [69, "Volunteer Recruitment & Matching", ["Advertise opportunities & screen volunteer applications", "Match volunteers to roles based on skills & availability", "Induct & brief volunteers on expectations & safeguarding", "Review placement at 3 months & plan ongoing engagement"],    "Best practice: 80%+ volunteer placement rate; 12-month retention rate >50%; 100+ hours contributed per active volunteer per year; satisfaction >80%",  3],
  [70, "Compensation Benchmarking",        ["Participate in or purchase sector salary survey data", "Map all roles to benchmark job families", "Identify pay equity gaps & outliers", "Recommend pay adjustments to leadership & board"],    "Best practice: annual benchmarking review; 80%+ of roles within ±10% of sector median; gender pay gap published; pay equity review completed",  3],

  // ── Technology & Data ──────────────────────────────────────────────────────
  [71, "IT Systems Health Monitoring",     ["Configure monitoring alerts & dashboards", "Review system performance & incident logs daily", "Investigate & resolve incidents within SLA", "Produce monthly health report & trend analysis"],    "Best practice: 99.5%+ system uptime; MTTR <4 hours for critical systems; zero recurring incidents; reviewed monthly by IT governance board",  1],
  [72, "Software Licence Management",      ["Audit installed software vs licence entitlements", "Remove unused licences & right-size contracts", "Update licence register & set renewal reminders", "Review spend vs value & negotiate renewals"],    "Best practice: 100% licence compliance; renewals reviewed 90 days in advance; cost per licence benchmarked annually; 10–20% savings from rationalisation",  3],
  [73, "CRM Data Quality Monitoring",      ["Run weekly automated data quality checks", "Generate exception report & assign data corrections", "Track resolution rate & time to correction", "Publish monthly data quality score to CRM team"],    "Best practice: 95%+ data quality score; anomaly detection run weekly; corrections completed within 48 hours; quality score reviewed in monthly CRM governance meeting",  2],
  [74, "Cybersecurity Risk Management",    ["Conduct quarterly vulnerability assessment", "Prioritise & remediate critical vulnerabilities within 30 days", "Deliver phishing simulation & security awareness training", "Report to IT governance & update risk register"],    "Best practice: critical vulnerability closure within 30 days; phishing click rate <5% after training; 100% security training completion annually",  1],
  [75, "CRM Configuration Management",     ["Log all CRM change requests in backlog", "Test & validate changes in sandbox environment", "Deploy changes to production & communicate to users", "Monitor for errors & capture user adoption metrics"],    "Best practice: 99%+ CRM uptime; 80%+ user adoption rate; workflow error rate <1%; change requests resolved within 10 working days",  2],
  [76, "Data Privacy Governance",          ["Maintain ROPA & data asset inventory", "Conduct DPIA for all new processing activities", "Respond to SARs within statutory timescale", "Report privacy incidents & notify ICO if required"],    "GDPR best practice: SAR response within 30 calendar days; 100% DPIA completion before processing; breach notification to ICO within 72 hours; ROPA reviewed annually",  1],
  [77, "Cross-Platform Data Integration",  ["Map data flows & integration points between systems", "Build or configure integration connectors", "Test end-to-end data flows & validate accuracy", "Monitor integration health & resolve sync errors within 24 hours"],    "Best practice: 99%+ integration uptime; <0.1% sync error rate; data latency <1 hour; integration health dashboard reviewed daily",  2],
  [78, "Data Warehouse Management",        ["Monitor ETL pipeline runs & data refresh schedules", "Investigate & resolve failed pipeline runs", "Validate data quality in warehouse vs source systems", "Govern access & publish data freshness SLA to users"],    "Best practice: 99%+ pipeline reliability; report load time <5 seconds; data refreshed within 24 hours; self-service adoption rate >60% of report users",  2],
  [79, "Digital Transformation Roadmap",   ["Assess current digital capability & maturity", "Prioritise initiatives against strategic impact & effort", "Execute roadmap & track delivery milestones", "Review value realisation at 12 months post-implementation"],    "Best practice: 80%+ roadmap on-time delivery; value realisation tracked at 6 & 12 months; stakeholder NPS >60; quarterly board progress report",  3],
  [80, "AI Model Governance",              ["Register AI model & complete pre-deployment assessment", "Test for accuracy, bias & fairness", "Obtain governance sign-off from ethics review panel", "Monitor model performance & retrain on schedule"],    "Best practice: model accuracy >85% for decision-support; quarterly bias reviews; 100% governance compliance before deployment; human override available for all automated decisions",  2],
  [81, "Technology Spend Reporting",       ["Collect actuals from finance & IT procurement records", "Map spend to technology categories & business units", "Compare to budget & ROI targets; identify anomalies", "Present technology spend dashboard to leadership monthly"],    "Best practice: tech spend within 5% of budget; ROI tracked for all investments >£10k; monthly reporting to IT Steering Committee; benchmarked against 5–8% of operating costs",  3],
  [82, "AI-Powered IT Helpdesk",           ["Receive & triage ticket via AI chatbot or portal", "AI resolves Tier-1 issues automatically", "Escalate unresolved issues to IT technician", "Close ticket, gather user satisfaction score & update knowledge base"],    "Best practice: first contact resolution >80%; critical ticket resolution <4 hours; user satisfaction >85%; 40%+ of Tier-1 queries resolved by AI without agent",  2],
  [83, "Cloud Cost Optimisation",          ["Pull cloud cost reports & usage data from provider", "Identify underutilised resources & reserved instance opportunities", "Implement cost optimisation actions", "Track savings vs baseline & report monthly to IT governance"],    "Best practice: 20–30% cost savings vs pre-optimisation baseline; resource utilisation >70%; cost anomalies flagged within 24 hours; reviewed in monthly cloud governance meeting",  3],
  [84, "Data Retention Management",        ["Audit data assets against retention policy schedules", "Generate deletion & archival task list", "Execute approved deletions & archive ageing data", "Update retention register & report compliance status"],    "GDPR best practice: 100% policy compliance; overdue deletions resolved within 30 days; storage cost reduction tracked; annual data retention audit completed",  2],
  [85, "Vendor Due Diligence",             ["Identify vendor & initiate due diligence checklist", "Assess data processing, security & financial stability", "Obtain sign-off from DPO & Legal where required", "Onboard vendor & schedule annual review"],    "Best practice: 100% due diligence for vendors accessing personal data; vendor risk score reviewed annually; contract terms reviewed by Legal for all spend >£25k",  2],
  [86, "Business Continuity Planning",     ["Conduct annual BIA & update risk scenarios", "Test DR plan via tabletop or live failover exercise", "Review & update BCP documentation", "Brief all staff & board on current BCP status"],    "Best practice: annual DR test with documented results; RTO met in 100% of tests; plan reviewed and updated annually; board-approved BCP in place",  1],
  [87, "Enterprise Data Dictionary",       ["Identify critical data assets for documentation", "Capture metadata, definitions & data lineage", "Validate with data owners & update dictionary", "Publish dictionary & promote self-service adoption"],    "Best practice: 80%+ of critical data assets documented; metadata accuracy >90%; reviewed quarterly by data stewards; dictionary accessed by 60%+ of analysts",  3],
  [88, "AI Tools Governance",              ["Assess new AI tool against governance policy criteria", "Complete risk assessment & data privacy review", "Obtain approval from governance panel", "Monitor usage & audit compliance quarterly"],    "Best practice: governance assessment completed before any AI tool deployment; zero unauthorized AI tool usage; 100% staff training on responsible AI policy",  2],
  [89, "Software QA Management",           ["Define test plan & acceptance criteria", "Execute functional, regression & performance tests", "Log defects & manage resolution with development team", "Sign off release & monitor post-deployment for defect escape"],    "Best practice: 80%+ automated test coverage; defect escape rate <5%; 2-week release cycles; UAT sign-off required before production deployment",  2],
  [90, "Master Data Management",           ["Identify master data domains & governance owners", "Detect & merge duplicates using matching rules", "Establish golden record & propagate to source systems", "Monitor data quality & report MDM health monthly"],    "Best practice: <0.5% duplicate rate; 95%+ golden record accuracy; 80%+ of source systems consuming master data; MDM platform reviewed annually",  2],
  [91, "Executive Insights Dashboards",    ["Gather requirements from senior leadership", "Design KPI framework & dashboard prototype", "Build, validate & publish dashboard to leadership", "Gather adoption feedback & iterate on a quarterly basis"],    "Best practice: 80%+ dashboard adoption by C-suite & board; insights reviewed weekly; decision cycle time reduced by 30%; quarterly dashboard review cycle",  2],
  [92, "Digital Accessibility Compliance", ["Audit all digital properties against WCAG 2.1 AA", "Prioritise & assign remediation tasks", "Implement fixes & retest affected components", "Publish accessibility statement & schedule annual audit"],    "Legal requirement (PSBAR/EqA): WCAG 2.1 AA compliance for all public-facing digital properties; 100% new content accessible before publish; annual full audit",  2],
  [93, "External Data Monitoring",         ["Identify priority external data sources & indicators", "Set up automated data feeds or scheduled extraction", "Analyse external data & generate strategic insights", "Distribute insights digest to leadership monthly"],    "Best practice: 3+ trusted external data sources integrated; insights distributed within 30 days of data release; data freshness reviewed monthly",  4],
  [94, "Knowledge Base Management",        ["Audit existing knowledge base content for accuracy", "Create or update articles based on support tickets & staff queries", "Publish & tag content for search optimisation", "Track search success rate & identify content gaps monthly"],    "Best practice: 80%+ search success rate; 70%+ of staff active monthly users; time-to-answer reduced by 40%; content reviewed at least annually",  3],
  [95, "API Lifecycle Management",         ["Document API specification & publish to developer portal", "Version & deprecate APIs with 90-day notice", "Monitor API usage, errors & SLA compliance", "Review & retire end-of-life APIs on schedule"],    "Best practice: 100% API documentation coverage; 90-day deprecation notice; error rate <0.1%; API health dashboard reviewed weekly",  2],
  [96, "Data Ethics Assessments",          ["Identify new data projects requiring ethics review", "Complete ethics assessment checklist & document risks", "Obtain sign-off from Ethics Review Panel", "Monitor & review post-deployment at 6 months"],    "Best practice: ethics assessment completed before any new data processing; 100% of flagged issues resolved before go-live; ethics panel meets monthly",  2],
  [97, "Identity & Access Management",     ["Process joiner/mover/leaver access requests within SLA", "Conduct quarterly access rights review across all systems", "Remove or adjust access within 1 day of notification", "Audit privileged accounts & report to IT governance"],    "Best practice: provisioning within 1 working day; quarterly access reviews; zero orphaned accounts; MFA enforced for all staff accessing sensitive data",  2],
  [98, "Security Incident Response",       ["Detect & classify security incident via monitoring tools", "Contain incident & activate incident response team", "Investigate, eradicate & recover affected systems", "Conduct post-incident review & notify regulator if required"],    "Best practice: detection within 1 hour; containment within 4 hours for critical; GDPR breach notification to ICO within 72 hours; post-incident review within 5 days",  1],
  [99, "Technology Architecture Review",   ["Assess current architecture against strategic roadmap", "Identify technical debt items & integration gaps", "Document architecture decisions & update reference architecture", "Present architecture scorecard to IT Steering Committee"],    "Best practice: annual architecture review; tech debt backlog maintained & prioritised; 80%+ architecture alignment score; reviewed by senior engineer panel",  3],
  [100,"Digital Experience Optimisation",  ["Define optimisation hypothesis & success metrics", "Design A/B or multivariate test & build variants", "Run experiment & collect statistically significant data", "Analyse results & implement winning variant"],    "Best practice: 10–20% conversion rate improvement per optimisation cycle; 2-week test velocity; 70%+ of tests show statistically significant uplift; CRO programme reviewed quarterly",  4],
];

async function main() {
  const client = await pool.connect();
  try {
    console.log(`Updating ${DATA.length} processes…`);
    let updated = 0;
    for (const [id, name, tasks, benchmark, priority] of DATA) {
      const xml = bpmn(`Process_${id}`, name, tasks);
      await client.query(
        `UPDATE processes SET bpmn = $1, industry_benchmark = $2, priority = $3 WHERE id = $4`,
        [xml, benchmark, priority, id],
      );
      updated++;
      if (updated % 10 === 0) console.log(`  ${updated}/${DATA.length} done`);
    }
    console.log(`Done — ${updated} processes updated.`);
  } finally {
    client.release();
    await pool.end();
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
