import {
  db,
  initiatives,
  processesTable,
  strategicGoalInitiativesTable,
  strategicGoalsTable,
  tenants,
  tenantStrategyTable,
} from "@workspace/db";

const processes = [
  { number: 1, category: "Strategy & Governance", processName: "Define multi-year cause-area strategy and funding thesis", aiAgent: "Philanthropy Strategy Agent", purpose: "Analyze needs, trends, and prior outcomes to recommend strategic priorities.", inputs: "Historical impact data; beneficiary needs assessments; macro trends; board priorities", outputs: "3-year strategy options; recommended focus areas; risk-adjusted portfolio view", humanInTheLoop: "CEO / Board validates strategic direction", kpi: "Program ROI; % portfolio aligned to strategy; strategy refresh cycle time", estimatedValueImpact: "Higher allocation effectiveness; reduced strategy rework" },
  { number: 2, category: "Strategy & Governance", processName: "Set annual program budget envelopes by geography and cause", aiAgent: "Funding Allocation Agent", purpose: "Optimize yearly funding envelopes across programs and regions.", inputs: "Annual budget; prior spend; pipeline demand; impact scores", outputs: "Recommended budget envelopes; scenario analysis; trade-off view", humanInTheLoop: "CFO and Program Heads approve final allocations", kpi: "Impact per dollar; budget variance; funding coverage ratio", estimatedValueImpact: "Improved capital allocation and fewer budget overruns" },
  { number: 3, category: "Strategy & Governance", processName: "Prepare board and committee meeting agendas and packs", aiAgent: "Board Governance Agent", purpose: "Compile decision-ready materials for board and committee meetings.", inputs: "Board calendar; management reports; risk issues; committee charters", outputs: "Agenda drafts; board packs; action tracker", humanInTheLoop: "Board Secretary reviews and finalizes materials", kpi: "Board pack preparation time; on-time distribution rate", estimatedValueImpact: "Lower administrative effort and faster governance cycles" },
  { number: 4, category: "Strategy & Governance", processName: "Design outcomes framework and impact thesis for each portfolio", aiAgent: "Impact Thesis Agent", purpose: "Define measurable outcomes and theories of change for funded portfolios.", inputs: "Research evidence; SDG mappings; prior portfolio results", outputs: "Logic models; outcome trees; measurement plans", humanInTheLoop: "Program Directors validate assumptions and indicators", kpi: "Outcome measurability score; % programs with clear logic model", estimatedValueImpact: "Stronger impact discipline and better evaluation quality" },
  { number: 5, category: "Strategy & Governance", processName: "Maintain enterprise risk register for fundraising, grants, and operations", aiAgent: "Risk Policy Agent", purpose: "Identify, classify, and prioritize enterprise risks across the charity.", inputs: "Audit findings; incidents; policy obligations; operational data", outputs: "Risk heatmap; mitigation actions; risk register updates", humanInTheLoop: "Risk Committee confirms ratings and mitigation owners", kpi: "Open high-risk items; overdue mitigations; incident frequency", estimatedValueImpact: "Reduced compliance and operational losses" },
  { number: 6, category: "Strategy & Governance", processName: "Conduct annual stakeholder perception and trust survey analysis", aiAgent: "Stakeholder Insights Agent", purpose: "Synthesize stakeholder feedback to identify trust gaps and advocacy opportunities.", inputs: "Survey responses; media mentions; donor feedback; beneficiary interviews", outputs: "Perception dashboard; gap analysis; recommended actions", humanInTheLoop: "CEO reviews and selects priorities for trust-building", kpi: "Stakeholder Net Promoter Score; perception improvement rate", estimatedValueImpact: "Better stakeholder alignment and donor retention" },
  { number: 7, category: "Strategy & Governance", processName: "Evaluate charity performance against strategic KPIs quarterly", aiAgent: "Performance Analytics Agent", purpose: "Generate quarterly scorecards against strategic goals for executive review.", inputs: "Operational data; program reports; financial results; KPI targets", outputs: "Quarterly scorecard; traffic light report; executive summary", humanInTheLoop: "Executive team reviews deviations and corrective actions", kpi: "KPI attainment rate; review cycle time; action closure rate", estimatedValueImpact: "Earlier course correction and better strategic agility" },
  { number: 8, category: "Strategy & Governance", processName: "Benchmark against peer nonprofits on key impact metrics", aiAgent: "Benchmarking Intelligence Agent", purpose: "Compare organizational performance with sector peers to identify gaps and best practices.", inputs: "Sector databases; peer reports; GuideStar/Charity Navigator data", outputs: "Benchmark comparison report; opportunity heatmap; improvement roadmap", humanInTheLoop: "Strategy team interprets findings and sets targets", kpi: "Percentile rank vs peers; benchmark gap closure rate", estimatedValueImpact: "Informed target-setting and competitive positioning" },
  { number: 9, category: "Strategy & Governance", processName: "Develop and review annual theory of change narrative", aiAgent: "Theory of Change Agent", purpose: "Articulate and update how the charity's work drives lasting social change.", inputs: "Program outcomes; external research; board feedback; beneficiary stories", outputs: "Updated theory of change document; visual summary; comms brief", humanInTheLoop: "Board and leadership team approve narrative", kpi: "Stakeholder clarity score; ToC currency (months since last update)", estimatedValueImpact: "Clearer mission alignment and stronger donor confidence" },
  { number: 10, category: "Strategy & Governance", processName: "Assess and prioritize new cause areas or geographies", aiAgent: "Cause Exploration Agent", purpose: "Evaluate potential new focus areas using evidence, need, and capacity criteria.", inputs: "Needs assessments; funding landscape data; organizational capacity review", outputs: "Cause prioritization matrix; go/no-go recommendation; risks and assumptions", humanInTheLoop: "Board sub-committee makes final expansion decision", kpi: "New areas evaluated per year; expansion success rate", estimatedValueImpact: "Better expansion decisions and reduced strategic drift" },
  { number: 11, category: "Fundraising & Donor Management", processName: "Identify and score major gift donor prospects", aiAgent: "Prospect Research Agent", purpose: "Surface high-potential donors from CRM and external wealth databases.", inputs: "CRM contact data; wealth screening feeds; giving history; engagement scores", outputs: "Ranked prospect list; engagement heat scores; recommended approaches", humanInTheLoop: "Major gifts officer reviews and selects outreach targets", kpi: "Prospect conversion rate; pipeline value; cost per prospect identified", estimatedValueImpact: "Higher major gift revenue with less manual research" },
  { number: 12, category: "Fundraising & Donor Management", processName: "Write personalized major donor cultivation letters and proposals", aiAgent: "Donor Engagement Writer Agent", purpose: "Draft personalized outreach and proposals tailored to each donor's giving history and interests.", inputs: "Donor profile; giving history; program alignment; relationship notes", outputs: "Personalized letter drafts; gift proposals; follow-up schedules", humanInTheLoop: "Relationship manager reviews and approves before sending", kpi: "Proposal acceptance rate; time to draft; donor engagement score uplift", estimatedValueImpact: "Higher gift conversion rates through personalized outreach" },
  { number: 13, category: "Fundraising & Donor Management", processName: "Segment and target direct mail and email donor campaigns", aiAgent: "Campaign Segmentation Agent", purpose: "Build targeted donor segments for each fundraising campaign using behavioral data.", inputs: "CRM data; giving history; engagement scores; campaign objectives", outputs: "Campaign segments; channel assignments; expected response rates", humanInTheLoop: "Fundraising manager approves segments and exclusions", kpi: "Response rate; average gift size; cost per dollar raised", estimatedValueImpact: "Higher campaign ROI through precision targeting" },
  { number: 14, category: "Fundraising & Donor Management", processName: "Automate donor acknowledgement and stewardship communications", aiAgent: "Stewardship Automation Agent", purpose: "Trigger personalized acknowledgements and stewardship touch-points at the right time.", inputs: "Gift transactions; donor preferences; milestone triggers; CRM workflows", outputs: "Acknowledgement emails; thank-you letters; impact updates; anniversary reminders", humanInTheLoop: "Fundraising team spot-checks for high-value donors", kpi: "Acknowledgement turnaround time; stewardship touch frequency; donor retention rate", estimatedValueImpact: "Improved donor retention and reduced admin workload" },
  { number: 15, category: "Fundraising & Donor Management", processName: "Predict donor churn and design win-back strategies", aiAgent: "Donor Retention Agent", purpose: "Flag lapsing donors early and recommend personalised win-back interventions.", inputs: "Giving history; engagement signals; comms response rates; peer benchmarks", outputs: "Churn risk scores; win-back segment; recommended interventions", humanInTheLoop: "Fundraising team reviews priority list and approves outreach", kpi: "Lapsed donor reactivation rate; churn rate reduction; retention campaign ROI", estimatedValueImpact: "Higher donor lifetime value and lower attrition cost" },
  { number: 16, category: "Fundraising & Donor Management", processName: "Forecast annual fundraising revenue by channel and segment", aiAgent: "Revenue Forecasting Agent", purpose: "Model fundraising revenue across channels to support annual planning.", inputs: "Historical giving data; pipeline; campaign calendar; economic indicators", outputs: "12-month revenue forecast; channel breakdown; scenario models", humanInTheLoop: "CFO and Fundraising Director validate assumptions and sign off", kpi: "Forecast accuracy; revenue variance to plan; scenario coverage", estimatedValueImpact: "Better financial planning and reduced revenue surprises" },
  { number: 17, category: "Fundraising & Donor Management", processName: "Optimise fundraising event logistics and guest communications", aiAgent: "Event Coordination Agent", purpose: "Plan and manage fundraising event logistics, invitations, and follow-up.", inputs: "Event brief; guest list; venue constraints; budget; past event data", outputs: "Run-of-show; guest communication schedule; logistics checklist", humanInTheLoop: "Events manager reviews plan and confirms vendor bookings", kpi: "Event net revenue; attendance rate; post-event donor upgrade rate", estimatedValueImpact: "Higher event ROI and improved donor experience" },
  { number: 18, category: "Fundraising & Donor Management", processName: "Monitor and report on peer-to-peer fundraising campaigns", aiAgent: "P2P Analytics Agent", purpose: "Track peer-to-peer campaign performance and surface coaching opportunities for top fundraisers.", inputs: "P2P platform data; team and individual pages; donation transactions", outputs: "Live campaign dashboard; top performer report; coaching nudges", humanInTheLoop: "Fundraising team sends coaching nudges to key fundraisers", kpi: "P2P revenue; average fundraiser raised; team activation rate", estimatedValueImpact: "Increased P2P revenue through smarter coach-and-activate cycles" },
  { number: 19, category: "Fundraising & Donor Management", processName: "Manage digital fundraising platform integration and data hygiene", aiAgent: "Data Integration Agent", purpose: "Sync fundraising platform data to CRM and flag data quality issues.", inputs: "Fundraising platform exports; CRM records; duplicate detection rules", outputs: "Clean CRM records; sync logs; data quality alerts", humanInTheLoop: "Data team resolves flagged duplicates and anomalies", kpi: "Data match rate; duplicate rate; sync lag time", estimatedValueImpact: "Cleaner donor data leading to better targeting and compliance" },
  { number: 20, category: "Fundraising & Donor Management", processName: "Produce gift acceptance and donor recognition policy recommendations", aiAgent: "Policy Advisory Agent", purpose: "Review and recommend gift acceptance policies aligned with legal and ethical standards.", inputs: "Existing gift policy; legal obligations; donor proposals; sector benchmarks", outputs: "Updated gift policy draft; recognition schedule; risk flags", humanInTheLoop: "Legal counsel and board sub-committee approve policy", kpi: "Policy compliance rate; gift rejection rate; recognition accuracy", estimatedValueImpact: "Reduced compliance risk and stronger donor trust" },
  { number: 21, category: "Grant Management", processName: "Scan and identify new grant opportunities aligned to strategy", aiAgent: "Grant Discovery Agent", purpose: "Continuously monitor funder databases and government sources for relevant grant opportunities.", inputs: "Strategy priorities; funder databases; RSS feeds; geo and cause filters", outputs: "Weekly opportunity digest; alignment scores; deadline calendar", humanInTheLoop: "Grants team reviews digest and selects priority applications", kpi: "Opportunities identified per week; alignment score accuracy; applications submitted vs eligible", estimatedValueImpact: "More grant revenue with less manual scanning effort" },
  { number: 22, category: "Grant Management", processName: "Draft and review grant applications and supporting documents", aiAgent: "Grant Writing Agent", purpose: "Generate well-structured grant applications tailored to each funder's criteria.", inputs: "Funder brief; program data; impact evidence; prior applications; budget templates", outputs: "Full grant application draft; supporting document checklist; submission-ready package", humanInTheLoop: "Grants manager and program lead review and approve before submission", kpi: "Application success rate; time to draft; compliance score", estimatedValueImpact: "Higher grant win rate and reduced writing time" },
  { number: 23, category: "Grant Management", processName: "Manage grant compliance reporting calendar and deadlines", aiAgent: "Grant Compliance Agent", purpose: "Track all grant reporting obligations and alert teams ahead of deadlines.", inputs: "Grant agreements; reporting schedules; milestone dates; CRM/grants management system", outputs: "Compliance calendar; automated deadline reminders; completion status dashboard", humanInTheLoop: "Grants coordinator reviews and confirms report submissions", kpi: "On-time reporting rate; missed deadline count; compliance alert lead time", estimatedValueImpact: "Zero missed deadlines and improved funder relationships" },
  { number: 24, category: "Grant Management", processName: "Produce mid-term and final grant progress reports", aiAgent: "Grant Reporting Agent", purpose: "Compile narrative and financial progress reports aligned to funder requirements.", inputs: "Program activity logs; financial reports; KPI data; funder reporting templates", outputs: "Draft narrative report; financial summary; supporting evidence pack", humanInTheLoop: "Program Director reviews accuracy and approves before submission", kpi: "Report acceptance rate; revision cycles; average preparation time", estimatedValueImpact: "Faster reporting cycles and improved funder confidence" },
  { number: 25, category: "Grant Management", processName: "Monitor grant expenditure against approved budgets", aiAgent: "Grant Finance Agent", purpose: "Track actual vs approved grant spend and flag variances for corrective action.", inputs: "Grant agreements; approved budgets; finance system actuals; project codes", outputs: "Expenditure variance report; underspend/overspend alerts; reforecast recommendations", humanInTheLoop: "Finance and grants team jointly review and approve amendments", kpi: "Budget variance %; underspend rate; grant close-out time", estimatedValueImpact: "Reduced grant clawbacks and improved financial stewardship" },
  { number: 26, category: "Grant Management", processName: "Coordinate site visits and funder relationship meetings", aiAgent: "Funder Relationship Agent", purpose: "Prepare briefing materials and logistics for funder site visits and relationship meetings.", inputs: "Funder profile; program updates; meeting agenda; stakeholder bios", outputs: "Visit briefing packs; talking points; post-visit action log", humanInTheLoop: "Relationship manager leads meeting and confirms key messages", kpi: "Funder satisfaction score; follow-on grant conversion rate; meeting prep time", estimatedValueImpact: "Stronger funder relationships and higher renewal rates" },
  { number: 27, category: "Grant Management", processName: "Manage multi-funder consortium grant reporting", aiAgent: "Consortium Grants Agent", purpose: "Coordinate reporting across multiple consortium partners for shared grants.", inputs: "Consortium agreements; partner activity data; shared reporting templates", outputs: "Consolidated consortium report; partner contribution summary; funder submission", humanInTheLoop: "Lead partner reviews and submits consolidated report", kpi: "Consortium report accuracy; submission timeline; partner data quality", estimatedValueImpact: "Reduced consortium coordination effort and compliance risk" },
  { number: 28, category: "Grant Management", processName: "Evaluate and score incoming grant proposals from sub-grantees", aiAgent: "Sub-grant Assessment Agent", purpose: "Score and rank sub-grantee proposals against funding criteria.", inputs: "Sub-grantee applications; scoring rubrics; strategic priorities; due diligence checklists", outputs: "Ranked proposal scores; funding recommendations; due diligence summaries", humanInTheLoop: "Grants committee reviews shortlist and makes final award decisions", kpi: "Scoring consistency; award decision time; sub-grantee impact outcomes", estimatedValueImpact: "More objective grant allocation and faster decision cycles" },
  { number: 29, category: "Grant Management", processName: "Maintain grants management system data accuracy and hygiene", aiAgent: "Grants Data Agent", purpose: "Keep the grants management system current, accurate, and audit-ready.", inputs: "Grants management system records; award letters; amendments; reporting updates", outputs: "Data quality reports; anomaly alerts; updated system records", humanInTheLoop: "Grants coordinator reviews and resolves flagged data issues", kpi: "Data accuracy rate; system update lag; audit-ready record %", estimatedValueImpact: "Cleaner data for reporting, compliance, and forecasting" },
  { number: 30, category: "Grant Management", processName: "Build and maintain a funder intelligence and landscape database", aiAgent: "Funder Intelligence Agent", purpose: "Maintain a curated database of funder priorities, cycles, and contact information.", inputs: "Funder websites; annual reports; IRS 990 filings; conference intelligence", outputs: "Funder profiles database; priority shift alerts; relationship owner map", humanInTheLoop: "Grants Director reviews major updates and validates intelligence", kpi: "Database currency (% updated within 12 months); funder coverage rate", estimatedValueImpact: "Smarter grant targeting and relationship management" },
  { number: 31, category: "Marketing, Brand & Communications", processName: "Develop annual content calendar across all channels", aiAgent: "Content Strategy Agent", purpose: "Build a 12-month content plan aligned to fundraising and program cycles.", inputs: "Fundraising calendar; program milestones; audience segments; past engagement data", outputs: "Integrated content calendar; channel breakdown; content briefs", humanInTheLoop: "Comms Director approves calendar and adjusts for key moments", kpi: "Content calendar adherence rate; cross-channel alignment score; content engagement rate", estimatedValueImpact: "More consistent brand presence and higher audience engagement" },
  { number: 32, category: "Marketing, Brand & Communications", processName: "Generate and edit social media posts and campaigns", aiAgent: "Social Media Content Agent", purpose: "Produce high-quality, on-brand social content optimized for each platform.", inputs: "Content brief; brand guidelines; platform best practices; audience insights", outputs: "Platform-specific post drafts; image briefs; scheduling recommendations", humanInTheLoop: "Comms team reviews tone and accuracy before scheduling", kpi: "Engagement rate; reach; content approval cycle time", estimatedValueImpact: "More consistent social posting with less team effort" },
  { number: 33, category: "Marketing, Brand & Communications", processName: "Draft, test, and send donor email newsletters", aiAgent: "Email Marketing Agent", purpose: "Produce segmented email newsletters and track performance.", inputs: "Content calendar; CRM segments; email template; past open/click rates", outputs: "Newsletter draft; A/B test variants; send schedule; performance report", humanInTheLoop: "Comms lead reviews copy and approves before send", kpi: "Open rate; click-through rate; unsubscribe rate; conversion rate", estimatedValueImpact: "Higher email engagement and donation uplift per campaign" },
  { number: 34, category: "Marketing, Brand & Communications", processName: "Monitor and respond to brand mentions and media coverage", aiAgent: "Media Monitoring Agent", purpose: "Track press, social, and digital mentions and flag issues or opportunities.", inputs: "Media monitoring feeds; social listening tools; keyword alerts; sentiment scores", outputs: "Daily media digest; sentiment summary; urgent alert notifications", humanInTheLoop: "Comms Director reviews escalated coverage and approves responses", kpi: "Response time to media queries; sentiment trend; coverage volume", estimatedValueImpact: "Faster brand protection and more proactive PR management" },
  { number: 35, category: "Marketing, Brand & Communications", processName: "Produce impact reports and annual review publications", aiAgent: "Impact Communications Agent", purpose: "Turn program and financial data into compelling impact narratives.", inputs: "KPI results; financial statements; beneficiary case studies; photography assets", outputs: "Annual report draft; impact infographics; executive summary", humanInTheLoop: "CEO and Comms Director approve final publication", kpi: "Publication timeline; donor readership rate; report-driven gift uplift", estimatedValueImpact: "More compelling reporting leading to increased donor confidence" },
  { number: 36, category: "Marketing, Brand & Communications", processName: "Manage SEO and paid digital advertising campaigns", aiAgent: "Digital Marketing Agent", purpose: "Optimize organic search and manage paid campaigns to drive traffic and donations.", inputs: "Website analytics; keyword data; ad budgets; campaign objectives", outputs: "SEO recommendations; ad copy variants; campaign performance report", humanInTheLoop: "Digital team reviews ad creative and confirms spend levels", kpi: "Organic traffic growth; cost per acquisition; ROAS; ad conversion rate", estimatedValueImpact: "Higher digital acquisition at lower cost per donor" },
  { number: 37, category: "Marketing, Brand & Communications", processName: "Localize communications for regional audiences and languages", aiAgent: "Localization Agent", purpose: "Adapt global communications content for regional language, cultural, and regulatory requirements.", inputs: "Master content; regional guidelines; glossary; cultural sensitivity notes", outputs: "Localized content variants; quality review checklist; approved translations", humanInTheLoop: "Regional comms lead reviews cultural accuracy before publishing", kpi: "Translation accuracy score; localization cycle time; regional engagement uplift", estimatedValueImpact: "Stronger regional resonance and improved campaign effectiveness" },
  { number: 38, category: "Marketing, Brand & Communications", processName: "Manage influencer and ambassador engagement programs", aiAgent: "Ambassador Engagement Agent", purpose: "Identify, recruit, and coordinate charity ambassadors and influencer partnerships.", inputs: "Brand alignment criteria; influencer databases; campaign objectives; existing ambassador roster", outputs: "Ambassador shortlist; partnership briefs; engagement plan; reporting dashboard", humanInTheLoop: "Comms Director approves new ambassador partnerships", kpi: "Ambassador reach; campaign participation rate; ambassador-driven donations", estimatedValueImpact: "Extended brand reach and social proof at low cost" },
  { number: 39, category: "Marketing, Brand & Communications", processName: "Analyse audience sentiment and adapt messaging", aiAgent: "Audience Sentiment Agent", purpose: "Continuously analyse audience feedback to optimise message relevance.", inputs: "Social listening data; email response rates; survey results; focus group reports", outputs: "Sentiment trend report; message effectiveness scores; recommended adjustments", humanInTheLoop: "Brand team reviews recommendations and approves messaging changes", kpi: "Message resonance score; sentiment improvement; campaign conversion lift", estimatedValueImpact: "More effective messaging leading to higher audience conversion" },
  { number: 40, category: "Marketing, Brand & Communications", processName: "Produce crisis communications plans and reactive statements", aiAgent: "Crisis Comms Agent", purpose: "Prepare holding statements and reactive comms for reputational risk scenarios.", inputs: "Risk register; crisis scenarios; past incidents; stakeholder maps", outputs: "Crisis comms playbook; holding statements; spokesperson briefing notes", humanInTheLoop: "CEO and legal counsel review and approve all external statements", kpi: "Response time to crisis; stakeholder satisfaction post-crisis; reputational recovery score", estimatedValueImpact: "Faster, more coherent crisis response and reduced reputational damage" },
  { number: 41, category: "Program Delivery & Operations", processName: "Design beneficiary intake and eligibility assessment workflows", aiAgent: "Intake Design Agent", purpose: "Build structured intake processes that are fair, consistent, and data-driven.", inputs: "Program eligibility criteria; regulatory requirements; past intake data; accessibility needs", outputs: "Intake workflow map; assessment rubric; digital form design", humanInTheLoop: "Program Manager validates criteria and approves workflow", kpi: "Intake processing time; eligibility determination accuracy; applicant experience score", estimatedValueImpact: "Faster beneficiary onboarding and reduced manual review time" },
  { number: 42, category: "Program Delivery & Operations", processName: "Monitor real-time program delivery against milestones", aiAgent: "Program Monitoring Agent", purpose: "Track live program progress against milestones and surface risks early.", inputs: "Program plans; activity logs; milestone tracker; staff updates", outputs: "Live program dashboard; milestone status; risk flags; recommended actions", humanInTheLoop: "Program Director reviews dashboard and acts on flagged issues", kpi: "Milestone completion rate; program variance; issue resolution time", estimatedValueImpact: "Earlier risk detection and higher program delivery reliability" },
  { number: 43, category: "Program Delivery & Operations", processName: "Collect, clean, and analyse beneficiary outcome data", aiAgent: "Outcome Data Agent", purpose: "Aggregate and analyse beneficiary outcome data to inform program adjustments.", inputs: "Survey responses; intake records; program activity logs; external datasets", outputs: "Outcome analysis report; trend charts; anomaly flags; recommendations", humanInTheLoop: "Monitoring & Evaluation team interprets findings and validates conclusions", kpi: "Data completeness rate; outcome measurement coverage; insight-to-action cycle time", estimatedValueImpact: "Better evidence base for program decisions and funder reports" },
  { number: 44, category: "Program Delivery & Operations", processName: "Coordinate volunteer scheduling and shift management", aiAgent: "Volunteer Scheduling Agent", purpose: "Match volunteers to program shifts based on skills, availability, and demand.", inputs: "Volunteer profiles; shift requirements; availability data; past attendance", outputs: "Weekly shift roster; automated assignment notifications; conflict alerts", humanInTheLoop: "Volunteer coordinator reviews final schedule and resolves conflicts", kpi: "Shift fill rate; no-show rate; volunteer satisfaction score", estimatedValueImpact: "Higher shift fill rates with less coordinator effort" },
  { number: 45, category: "Program Delivery & Operations", processName: "Manage supplier and contractor procurement for programs", aiAgent: "Procurement Agent", purpose: "Automate supplier sourcing, comparison, and purchase order management.", inputs: "Procurement requirements; approved supplier list; budget; evaluation criteria", outputs: "Supplier shortlist; bid comparison; purchase order drafts; contract alerts", humanInTheLoop: "Operations Manager approves supplier selection and POs above threshold", kpi: "Procurement cycle time; cost savings vs budget; supplier compliance rate", estimatedValueImpact: "Faster procurement and better value for money" },
  { number: 46, category: "Program Delivery & Operations", processName: "Conduct beneficiary satisfaction surveys and feedback analysis", aiAgent: "Beneficiary Feedback Agent", purpose: "Design, distribute, and analyse satisfaction surveys to improve program quality.", inputs: "Survey design brief; beneficiary contact list; past feedback; program data", outputs: "Satisfaction survey; results analysis; improvement recommendations", humanInTheLoop: "Program team reviews findings and agrees priority improvements", kpi: "Survey response rate; Net Satisfaction Score; improvement implementation rate", estimatedValueImpact: "Higher beneficiary satisfaction and improved program quality" },
  { number: 47, category: "Program Delivery & Operations", processName: "Develop safeguarding incident reporting and case management workflows", aiAgent: "Safeguarding Agent", purpose: "Ensure timely, consistent, and compliant management of safeguarding reports.", inputs: "Safeguarding policy; incident reports; regulatory obligations; case management protocols", outputs: "Incident case log; escalation decision tree; report templates; compliance audit trail", humanInTheLoop: "Designated Safeguarding Lead reviews every case and approves actions", kpi: "Incident reporting time; case closure rate; compliance audit pass rate", estimatedValueImpact: "Reduced safeguarding risk and improved regulatory compliance" },
  { number: 48, category: "Program Delivery & Operations", processName: "Plan and coordinate international field missions and logistics", aiAgent: "Field Operations Agent", purpose: "Manage end-to-end logistics for international program delivery teams.", inputs: "Mission brief; travel policy; visa requirements; security protocols; budget", outputs: "Travel itineraries; logistics checklist; risk assessment; cost reconciliation", humanInTheLoop: "Operations Director approves mission plan and security clearance", kpi: "Mission preparation time; cost variance; field team safety incidents", estimatedValueImpact: "Faster mission planning and reduced operational risk" },
  { number: 49, category: "Program Delivery & Operations", processName: "Generate program budget forecasts and spending alerts", aiAgent: "Program Finance Agent", purpose: "Project program spend trajectories and flag budget variances proactively.", inputs: "Approved budgets; actuals to date; pipeline commitments; historical run rates", outputs: "Spend forecast; variance report; overspend alerts; reforecast recommendations", humanInTheLoop: "Program and finance leads jointly review forecasts monthly", kpi: "Forecast accuracy; overspend incidents; budget utilization rate", estimatedValueImpact: "Fewer program budget surprises and better financial oversight" },
  { number: 50, category: "Program Delivery & Operations", processName: "Design and manage learning and adaptation cycles for programs", aiAgent: "Program Learning Agent", purpose: "Capture program learnings and drive systematic adaptation cycles.", inputs: "Evaluation reports; staff reflections; beneficiary feedback; external evidence", outputs: "Learning log; adaptation recommendations; updated program design", humanInTheLoop: "Program Director reviews learnings and approves design changes", kpi: "Learning cycle frequency; % recommendations implemented; program improvement rate", estimatedValueImpact: "More adaptive programs and higher long-term impact" },
  { number: 51, category: "Finance & Compliance", processName: "Prepare monthly management accounts and variance analysis", aiAgent: "Financial Reporting Agent", purpose: "Automate monthly management account production and highlight key variances.", inputs: "Finance system trial balance; budget data; prior month actuals; narrative templates", outputs: "Management accounts pack; variance commentary; executive dashboard", humanInTheLoop: "CFO reviews and approves pack before board distribution", kpi: "Reporting cycle time; commentary accuracy; board pack on-time delivery", estimatedValueImpact: "Faster month-end close and improved financial governance" },
  { number: 52, category: "Finance & Compliance", processName: "Manage accounts payable and invoice processing", aiAgent: "Accounts Payable Agent", purpose: "Automate invoice receipt, matching, approval routing, and payment scheduling.", inputs: "Supplier invoices; purchase orders; approval matrix; bank payment runs", outputs: "Matched invoices; payment run files; exception reports; supplier ledger updates", humanInTheLoop: "Finance team resolves exceptions and approves payment runs", kpi: "Invoice processing time; exception rate; payment on-time rate", estimatedValueImpact: "Faster payments and reduced finance admin cost" },
  { number: 53, category: "Finance & Compliance", processName: "Prepare statutory financial statements for charity commission filing", aiAgent: "Statutory Reporting Agent", purpose: "Compile annual statutory accounts aligned to charity GAAP/FRS 102 requirements.", inputs: "Full-year trial balance; audit schedules; notes templates; prior year accounts", outputs: "Draft statutory accounts; disclosure notes; trustee report; filing-ready documents", humanInTheLoop: "Auditors and CFO review and sign off statutory accounts", kpi: "Filing deadline compliance; audit adjustment count; disclosure completeness", estimatedValueImpact: "On-time regulatory filings and reduced audit adjustment cost" },
  { number: 54, category: "Finance & Compliance", processName: "Manage restricted and unrestricted fund accounting and reconciliation", aiAgent: "Fund Accounting Agent", purpose: "Maintain accurate fund-level accounting and reconcile restricted grant balances.", inputs: "Grant agreements; fund codes; transactions; opening fund balances", outputs: "Fund-by-fund balance sheet; restricted fund tracker; reconciliation report", humanInTheLoop: "Finance Director reviews fund balances and approves reconciliations", kpi: "Fund reconciliation accuracy; restricted fund breach alerts; close time", estimatedValueImpact: "Accurate fund reporting and zero funder compliance breaches" },
  { number: 55, category: "Finance & Compliance", processName: "Monitor and file Gift Aid and tax reclaim submissions", aiAgent: "Gift Aid Agent", purpose: "Automate Gift Aid eligibility checking, claim preparation, and HMRC submission.", inputs: "Donor gift transactions; Gift Aid declarations; eligibility rules; HMRC submission templates", outputs: "Gift Aid claim files; eligibility exceptions; submission confirmation", humanInTheLoop: "Finance team reviews claim before HMRC submission", kpi: "Gift Aid reclaim rate; submission accuracy; reclaim processing time", estimatedValueImpact: "Maximized Gift Aid revenue and reduced compliance risk" },
  { number: 56, category: "Finance & Compliance", processName: "Conduct internal audit reviews of key financial controls", aiAgent: "Internal Audit Agent", purpose: "Carry out risk-based internal audits of financial processes and controls.", inputs: "Audit plan; process documentation; transaction samples; control framework", outputs: "Audit findings report; control weakness log; management action plan", humanInTheLoop: "Internal audit lead reviews findings and agrees actions with management", kpi: "Control effectiveness rate; finding resolution time; repeat finding rate", estimatedValueImpact: "Stronger controls and reduced fraud/error exposure" },
  { number: 57, category: "Finance & Compliance", processName: "Manage payroll processing and PAYE compliance", aiAgent: "Payroll Processing Agent", purpose: "Automate monthly payroll calculations, deductions, and PAYE/NIC submissions.", inputs: "HR data changes; timesheet approvals; tax codes; pension contributions", outputs: "Payroll run files; payslips; HMRC RTI submissions; pension data files", humanInTheLoop: "HR and Finance jointly review payroll before final approval", kpi: "Payroll accuracy rate; on-time payment rate; PAYE compliance rate", estimatedValueImpact: "Error-free payroll with lower admin effort and compliance risk" },
  { number: 58, category: "Finance & Compliance", processName: "Produce cash flow forecasts and treasury management reports", aiAgent: "Treasury Management Agent", purpose: "Model cash inflows and outflows to optimize liquidity and investment decisions.", inputs: "Bank balances; income pipeline; committed expenditure; investment portfolio data", outputs: "13-week cash flow forecast; liquidity risk alerts; treasury recommendation", humanInTheLoop: "CFO reviews forecast and approves treasury actions", kpi: "Forecast accuracy; cash buffer maintenance; investment return vs benchmark", estimatedValueImpact: "Better liquidity management and optimized treasury returns" },
  { number: 59, category: "Finance & Compliance", processName: "Monitor charity regulatory compliance with GDPR, Charity Commission, etc.", aiAgent: "Regulatory Compliance Agent", purpose: "Track compliance obligations and alert on upcoming regulatory deadlines.", inputs: "Regulatory calendars; compliance obligation register; policy documents; incident logs", outputs: "Compliance status dashboard; upcoming obligation alerts; remediation actions", humanInTheLoop: "Compliance officer reviews status and escalates critical items", kpi: "Compliance score; overdue obligations; regulatory breach incidents", estimatedValueImpact: "Reduced regulatory risk and proactive compliance management" },
  { number: 60, category: "Finance & Compliance", processName: "Automate expense claims processing and policy compliance checks", aiAgent: "Expense Management Agent", purpose: "Review staff expense claims for policy compliance and route for approval.", inputs: "Expense claim submissions; expense policy; receipts; approval matrix", outputs: "Auto-approved claims; policy exception list; audit report; payment files", humanInTheLoop: "Line manager reviews flagged exceptions and approves payment", kpi: "Claim processing time; policy compliance rate; exception rate", estimatedValueImpact: "Faster reimbursements and better expense policy adherence" },
  { number: 61, category: "HR, Volunteers & Talent", processName: "Automate job posting, candidate screening, and shortlisting", aiAgent: "Recruitment Agent", purpose: "Accelerate hiring by automating job distribution, resume screening, and shortlisting.", inputs: "Job descriptions; hiring criteria; resume submissions; diversity targets", outputs: "Ranked candidate shortlist; screening summaries; interview schedule", humanInTheLoop: "Hiring manager reviews shortlist and confirms interview invitations", kpi: "Time to shortlist; quality of hire; diversity of shortlist", estimatedValueImpact: "Faster hiring and improved candidate quality with less admin" },
  { number: 62, category: "HR, Volunteers & Talent", processName: "Manage new employee and volunteer onboarding workflows", aiAgent: "Onboarding Agent", purpose: "Deliver structured, personalised onboarding journeys for new joiners and volunteers.", inputs: "Starter forms; role-specific onboarding plans; system access requirements; buddy assignments", outputs: "Personalised onboarding checklist; automated task reminders; completion tracking", humanInTheLoop: "Line manager confirms completion of critical onboarding milestones", kpi: "Onboarding completion rate; time to productivity; new joiner satisfaction score", estimatedValueImpact: "Faster onboarding, higher early retention, and lower manager burden" },
  { number: 63, category: "HR, Volunteers & Talent", processName: "Design and deliver staff learning and development plans", aiAgent: "L&D Planning Agent", purpose: "Map development needs to training solutions and build personalised learning journeys.", inputs: "Performance review data; skill gap assessments; available learning resources; career goals", outputs: "Individual development plans; training recommendations; learning pathway schedules", humanInTheLoop: "Line manager and employee agree final development plan", kpi: "Training completion rate; skill gap closure rate; staff satisfaction with L&D", estimatedValueImpact: "Better skilled teams and higher staff retention" },
  { number: 64, category: "HR, Volunteers & Talent", processName: "Automate employee performance review cycles and documentation", aiAgent: "Performance Management Agent", purpose: "Trigger and manage the end-to-end performance review cycle.", inputs: "Review cycle dates; competency frameworks; last review records; HR system data", outputs: "Review forms; automated reminders; completed review log; performance trend report", humanInTheLoop: "HR Business Partner reviews completion rates and supports managers", kpi: "Review completion rate on time; quality score of completed reviews; goal alignment rate", estimatedValueImpact: "Consistent performance management with lower HR admin overhead" },
  { number: 65, category: "HR, Volunteers & Talent", processName: "Monitor employee wellbeing and absence trends", aiAgent: "Wellbeing Analytics Agent", purpose: "Analyse absence, workload, and survey data to identify wellbeing risks.", inputs: "Absence records; workload data; pulse survey responses; EAP utilization data", outputs: "Wellbeing risk dashboard; team-level trends; recommended interventions", humanInTheLoop: "HR Director reviews risks and decides on support interventions", kpi: "Absence rate; wellbeing score; EAP utilisation rate; burnout risk flag count", estimatedValueImpact: "Reduced absenteeism and improved staff wellbeing" },
  { number: 66, category: "HR, Volunteers & Talent", processName: "Manage DBS and safeguarding checks for staff and volunteers", aiAgent: "Background Check Agent", purpose: "Automate DBS check requests, tracking, and renewal alerts.", inputs: "Staff/volunteer roster; DBS check status; renewal thresholds; role risk levels", outputs: "Check request submissions; renewal alert schedule; compliance status report", humanInTheLoop: "HR administrator resolves exceptions and confirms role clearance", kpi: "DBS check completion rate; overdue renewal count; compliance rate by role risk", estimatedValueImpact: "Reduced safeguarding risk and full DBS compliance" },
  { number: 67, category: "HR, Volunteers & Talent", processName: "Analyse staff satisfaction and design retention strategies", aiAgent: "Retention Strategy Agent", purpose: "Identify flight risk staff and recommend targeted retention interventions.", inputs: "Engagement survey data; exit interview themes; tenure data; market pay benchmarks", outputs: "Retention risk heatmap; stay interview recommendations; targeted actions", humanInTheLoop: "HR Director and line managers review risks and agree retention actions", kpi: "Staff turnover rate; flight risk identification accuracy; retention action completion rate", estimatedValueImpact: "Lower staff turnover and reduced recruitment cost" },
  { number: 68, category: "HR, Volunteers & Talent", processName: "Produce workforce planning and headcount forecasts", aiAgent: "Workforce Planning Agent", purpose: "Model future headcount needs based on program growth, attrition, and budget.", inputs: "Program pipeline; attrition data; budget constraints; strategic headcount plan", outputs: "12-month headcount forecast; skills gap projection; hiring plan", humanInTheLoop: "COO and HR Director review and approve workforce plan", kpi: "Forecast accuracy; vacancy fill rate; skills gap closure rate", estimatedValueImpact: "Better workforce readiness and reduced reactive hiring" },
  { number: 69, category: "HR, Volunteers & Talent", processName: "Automate volunteer recruitment, matching, and recognition", aiAgent: "Volunteer Management Agent", purpose: "Recruit, match, and celebrate volunteers efficiently at scale.", inputs: "Volunteer applications; opportunity briefs; skills matching criteria; recognition milestones", outputs: "Matched volunteer placements; automated recognition messages; impact summaries", humanInTheLoop: "Volunteer coordinator reviews placements and handles complex queries", kpi: "Volunteer placement rate; retention rate; hours contributed per volunteer", estimatedValueImpact: "More engaged volunteers and lower coordinator workload" },
  { number: 70, category: "HR, Volunteers & Talent", processName: "Review and benchmark staff compensation and pay equity", aiAgent: "Compensation Benchmarking Agent", purpose: "Analyse pay against market benchmarks and surface equity gaps.", inputs: "Current pay data; market salary surveys; role grades; equity analysis framework", outputs: "Pay benchmarking report; equity gap summary; recommended adjustments", humanInTheLoop: "HR Director and CFO jointly review and approve pay actions", kpi: "Pay equity score; % roles within benchmark band; time to complete benchmarking review", estimatedValueImpact: "Fairer pay, reduced attrition from pay dissatisfaction" },
  { number: 71, category: "Technology & Data", processName: "Monitor IT systems health, uptime, and incident response", aiAgent: "IT Operations Agent", purpose: "Continuously monitor system health and automate first-line incident triage.", inputs: "System monitoring alerts; uptime logs; incident tickets; SLA thresholds", outputs: "System health dashboard; incident triage reports; auto-resolved tickets; escalation alerts", humanInTheLoop: "IT Manager reviews escalated incidents and approves major changes", kpi: "System uptime %; mean time to resolve; incident recurrence rate", estimatedValueImpact: "Higher system reliability and faster incident resolution" },
  { number: 72, category: "Technology & Data", processName: "Manage software licence compliance and renewals", aiAgent: "Licence Management Agent", purpose: "Track software licence inventory, usage, and renewal dates.", inputs: "Software asset register; licence contracts; renewal dates; usage reports", outputs: "Licence status dashboard; renewal alerts; cost optimisation recommendations", humanInTheLoop: "IT Director reviews renewal decisions and approves contracts", kpi: "Licence compliance rate; renewal on-time rate; cost per licence", estimatedValueImpact: "Reduced licence risk and lower software spend" },
  { number: 73, category: "Technology & Data", processName: "Automate data quality monitoring across CRM and financial systems", aiAgent: "Data Quality Agent", purpose: "Continuously scan key systems for data quality issues and route corrections.", inputs: "CRM and finance system data; data quality rules; master data definitions", outputs: "Data quality score; anomaly alerts; correction task assignments", humanInTheLoop: "Data team reviews flagged issues and confirms resolution", kpi: "Data quality score; anomaly detection rate; time to correction", estimatedValueImpact: "Cleaner data across systems improving reporting and decision-making" },
  { number: 74, category: "Technology & Data", processName: "Manage cybersecurity risk assessments and awareness training", aiAgent: "Cybersecurity Agent", purpose: "Conduct recurring risk assessments and deliver targeted security awareness.", inputs: "Vulnerability scans; phishing test results; policy compliance data; staff training records", outputs: "Risk assessment report; targeted training assignments; remediation action log", humanInTheLoop: "IT Security lead reviews risks and approves remediation plans", kpi: "Vulnerability closure rate; phishing click rate; training completion rate", estimatedValueImpact: "Reduced cyber risk and stronger security culture" },
  { number: 75, category: "Technology & Data", processName: "Design and manage CRM system configuration and workflows", aiAgent: "CRM Management Agent", purpose: "Maintain CRM configuration, user permissions, and workflow automation.", inputs: "CRM admin logs; change requests; user feedback; business rules", outputs: "Updated CRM workflows; permission matrix; change log; documentation", humanInTheLoop: "CRM Administrator reviews changes before deployment", kpi: "CRM uptime; user adoption rate; workflow error rate; change deployment time", estimatedValueImpact: "More reliable CRM and higher user adoption" },
  { number: 76, category: "Technology & Data", processName: "Implement and govern data privacy and GDPR compliance controls", aiAgent: "Data Privacy Agent", purpose: "Maintain GDPR compliance controls, data subject requests, and privacy impact assessments.", inputs: "Data maps; privacy policies; subject access requests; breach reports", outputs: "Compliance dashboard; SAR responses; DPIA reports; breach notifications", humanInTheLoop: "Data Protection Officer reviews sensitive actions and approves responses", kpi: "SAR response time; DPIA completion rate; breach notification compliance rate", estimatedValueImpact: "GDPR compliance with reduced legal exposure" },
  { number: 77, category: "Technology & Data", processName: "Automate data integration between fundraising, CRM, and finance platforms", aiAgent: "Integration Agent", purpose: "Maintain reliable, real-time data flows between key operational systems.", inputs: "API configurations; data mapping rules; sync logs; error reports", outputs: "Integration health dashboard; sync reports; error resolution queue", humanInTheLoop: "Data/IT team resolves errors and approves mapping changes", kpi: "Integration uptime; sync error rate; data latency", estimatedValueImpact: "Reduced manual data entry and fewer reconciliation errors" },
  { number: 78, category: "Technology & Data", processName: "Build and maintain organisational data warehouse and reporting layer", aiAgent: "Data Engineering Agent", purpose: "Design and maintain the data warehouse and self-service reporting infrastructure.", inputs: "Source system schemas; business reporting requirements; data model documentation", outputs: "Updated data model; pipeline health reports; self-service dashboard templates", humanInTheLoop: "Data Engineering lead reviews model changes before production deployment", kpi: "Pipeline reliability; report load time; data freshness; user adoption of self-service", estimatedValueImpact: "Faster insights delivery and reduced BI bottlenecks" },
  { number: 79, category: "Technology & Data", processName: "Manage digital transformation roadmap prioritisation", aiAgent: "Digital Roadmap Agent", purpose: "Prioritise technology investments based on impact, cost, and strategic alignment.", inputs: "Tech backlog; business case submissions; strategic priorities; budget envelope", outputs: "Prioritised technology roadmap; business case assessments; investment recommendation", humanInTheLoop: "Executive team reviews and approves quarterly technology roadmap", kpi: "Roadmap delivery rate; value realisation vs business case; stakeholder satisfaction", estimatedValueImpact: "Better ROI on technology investments and faster transformation" },
  { number: 80, category: "Technology & Data", processName: "Monitor AI model performance and governance across the organisation", aiAgent: "AI Governance Agent", purpose: "Oversee AI model accuracy, bias risk, and compliance with AI governance policies.", inputs: "Model performance logs; bias audit results; governance policy; regulatory guidance", outputs: "AI performance dashboard; bias flags; governance compliance report; remediation actions", humanInTheLoop: "AI Ethics lead reviews flagged models and approves remediation", kpi: "Model accuracy rate; bias incident rate; governance compliance score", estimatedValueImpact: "Responsible AI deployment with reduced ethical and regulatory risk" },
  { number: 81, category: "Technology & Data", processName: "Automate reporting for technology spend and ROI tracking", aiAgent: "Tech Finance Agent", purpose: "Track technology expenditure and measure return on tech investments.", inputs: "IT cost centre data; project budgets; benefit realisation records; vendor contracts", outputs: "Tech spend dashboard; ROI report per initiative; anomaly alerts", humanInTheLoop: "CFO and IT Director review spend and ROI quarterly", kpi: "Tech spend vs budget; ROI achievement rate; cost per user", estimatedValueImpact: "Better control over technology spend and clearer ROI evidence" },
  { number: 82, category: "Technology & Data", processName: "Provide AI-powered internal helpdesk and IT support triage", aiAgent: "IT Helpdesk Agent", purpose: "Resolve common IT queries and triage complex issues to the right support tier.", inputs: "Helpdesk tickets; knowledge base; system health data; escalation matrix", outputs: "Auto-resolved tickets; triage summaries; escalation notes; knowledge base updates", humanInTheLoop: "IT support team handles escalated and complex issues", kpi: "First contact resolution rate; ticket resolution time; user satisfaction score", estimatedValueImpact: "Faster IT support and reduced helpdesk cost" },
  { number: 83, category: "Technology & Data", processName: "Monitor and optimise cloud infrastructure costs", aiAgent: "Cloud FinOps Agent", purpose: "Continuously right-size cloud resources and surface cost optimisation opportunities.", inputs: "Cloud billing data; resource utilisation logs; reserved instance inventory; tagging policies", outputs: "Cost optimisation recommendations; unused resource alerts; savings summary", humanInTheLoop: "IT Director approves resource changes and commitment purchases", kpi: "Cloud cost savings achieved; resource utilisation rate; cost anomaly detection rate", estimatedValueImpact: "Reduced cloud costs with maintained performance standards" },
  { number: 84, category: "Technology & Data", processName: "Design and enforce data retention and archiving policies", aiAgent: "Data Retention Agent", purpose: "Implement and monitor data retention policies across all systems.", inputs: "Data inventory; retention policy; regulatory requirements; system capacities", outputs: "Retention schedule; auto-archiving rules; deletion audit log; compliance status", humanInTheLoop: "Data Protection Officer approves retention schedules and deletion runs", kpi: "Policy compliance rate; storage cost reduction; overdue deletion rate", estimatedValueImpact: "GDPR compliance and reduced storage costs" },
  { number: 85, category: "Technology & Data", processName: "Conduct technology vendor due diligence and contract reviews", aiAgent: "Vendor Due Diligence Agent", purpose: "Assess vendor security, reliability, and contractual terms before procurement.", inputs: "Vendor questionnaires; contract drafts; security certifications; reference checks", outputs: "Due diligence report; risk summary; contract negotiation notes; approval recommendation", humanInTheLoop: "IT Director and legal review vendor reports and sign off contracts", kpi: "Due diligence completion rate; vendor risk score; contract review cycle time", estimatedValueImpact: "Reduced vendor risk and better contract outcomes" },
  { number: 86, category: "Technology & Data", processName: "Automate business continuity planning and DR testing schedules", aiAgent: "Business Continuity Agent", purpose: "Maintain and test business continuity and disaster recovery plans.", inputs: "BCP documents; DR test schedules; system dependency maps; incident history", outputs: "Updated BCP; DR test reports; gap analysis; recovery time estimates", humanInTheLoop: "COO reviews BCP updates and approves DR test results", kpi: "DR test completion rate; recovery time objective met %; plan currency (months since update)", estimatedValueImpact: "Reduced operational disruption risk and improved resilience" },
  { number: 87, category: "Technology & Data", processName: "Develop and maintain an enterprise data dictionary and metadata catalogue", aiAgent: "Metadata Management Agent", purpose: "Build and govern a central metadata catalogue to support data literacy.", inputs: "Source system schemas; existing documentation; data steward input; taxonomy standards", outputs: "Data dictionary; metadata catalogue; ownership register; change log", humanInTheLoop: "Data Governance lead reviews and approves new definitions", kpi: "Dictionary coverage rate; metadata accuracy score; data steward adoption rate", estimatedValueImpact: "Improved data literacy and faster time to insight" },
  { number: 88, category: "Technology & Data", processName: "Manage and govern use of AI tools and LLMs across the organisation", aiAgent: "AI Usage Governance Agent", purpose: "Set and enforce policies for responsible use of AI tools by staff.", inputs: "AI tool inventory; usage logs; policy framework; risk assessments", outputs: "AI usage policy; compliance reports; training requirements; approved tool list", humanInTheLoop: "Executive sponsor and legal review AI usage policy and approvals", kpi: "Policy adoption rate; unauthorized AI tool usage incidents; training completion rate", estimatedValueImpact: "Responsible AI use with reduced legal and reputational risk" },
  { number: 89, category: "Technology & Data", processName: "Automate test management and quality assurance for software releases", aiAgent: "QA Automation Agent", purpose: "Design and run automated test suites for software releases and integrations.", inputs: "Release notes; test cases; system configurations; regression test history", outputs: "Test execution reports; defect logs; release readiness assessment", humanInTheLoop: "QA lead reviews test results and approves go/no-go for release", kpi: "Test coverage %; defect escape rate; release cycle time", estimatedValueImpact: "Higher software quality with lower manual QA effort" },
  { number: 90, category: "Technology & Data", processName: "Design and implement master data management for key entities", aiAgent: "Master Data Agent", purpose: "Establish and maintain golden records for key data entities across systems.", inputs: "Source system data; deduplication rules; entity resolution algorithms; stewardship workflows", outputs: "Golden record repository; match/merge log; data quality metrics; ownership register", humanInTheLoop: "Data stewards review unresolved matches and confirm golden records", kpi: "Duplicate rate reduction; golden record accuracy; master data adoption rate", estimatedValueImpact: "Consistent, trustworthy data across all systems" },
  { number: 91, category: "Technology & Data", processName: "Deliver AI-driven insights dashboards for senior leadership", aiAgent: "Executive Insights Agent", purpose: "Generate auto-updated dashboards with AI-surfaced insights for executive decision-making.", inputs: "Financial data; program KPIs; fundraising pipeline; HR metrics; external indicators", outputs: "Executive dashboard; natural language insight summaries; trend alerts", humanInTheLoop: "COO reviews dashboards weekly and flags priorities for deeper analysis", kpi: "Dashboard adoption rate; insight accuracy; decision cycle time reduction", estimatedValueImpact: "Faster, better-informed executive decisions" },
  { number: 92, category: "Technology & Data", processName: "Support digital accessibility compliance across all platforms", aiAgent: "Accessibility Agent", purpose: "Audit digital channels for accessibility compliance and generate remediation recommendations.", inputs: "Website and app components; WCAG guidelines; accessibility audit reports; user testing", outputs: "Accessibility audit report; remediation backlog; prioritised fix list", humanInTheLoop: "Digital team reviews audit results and approves remediation sprint", kpi: "WCAG compliance rate; accessibility issue closure rate; user accessibility score", estimatedValueImpact: "Broader digital reach and reduced legal accessibility risk" },
  { number: 93, category: "Technology & Data", processName: "Monitor external data feeds and open data sources for programme insights", aiAgent: "External Data Agent", purpose: "Continuously ingest and analyse external open data relevant to program contexts.", inputs: "Government statistics; third-sector reports; weather and environmental data; economic indicators", outputs: "External data digest; correlation insights; alert notifications; analyst-ready datasets", humanInTheLoop: "Data analyst reviews insights and validates relevance for program decisions", kpi: "External data source coverage; insight utilisation rate; data freshness", estimatedValueImpact: "Richer program context and better evidence-based decisions" },
  { number: 94, category: "Technology & Data", processName: "Build and manage internal knowledge base and self-service tools", aiAgent: "Knowledge Management Agent", purpose: "Maintain a structured, searchable internal knowledge repository.", inputs: "Process documentation; past project outputs; policy documents; staff Q&A", outputs: "Updated knowledge base; search analytics; content gap recommendations", humanInTheLoop: "Knowledge Manager reviews gaps and commissions new content", kpi: "Search success rate; knowledge base usage; time-to-answer reduction", estimatedValueImpact: "Reduced duplicated effort and faster staff self-service" },
  { number: 95, category: "Technology & Data", processName: "Automate API management, documentation, and versioning", aiAgent: "API Management Agent", purpose: "Manage API lifecycle including documentation, versioning, and deprecation.", inputs: "API definitions; usage logs; developer feedback; versioning policy", outputs: "Updated API documentation; deprecation notices; version changelog; usage reports", humanInTheLoop: "API Product Owner approves deprecations and breaking changes", kpi: "API documentation coverage; deprecation notice lead time; API error rate", estimatedValueImpact: "More reliable APIs and better developer experience" },
  { number: 96, category: "Technology & Data", processName: "Produce data ethics assessments for new technology initiatives", aiAgent: "Data Ethics Agent", purpose: "Assess data ethics implications of new technology or AI deployments.", inputs: "Initiative briefs; data sources used; algorithmic decision logic; stakeholder groups affected", outputs: "Ethics assessment report; risk flagging; recommended mitigations; go/no-go recommendation", humanInTheLoop: "Data Ethics Board reviews assessments and approves new deployments", kpi: "Assessment completion rate before deployment; flagged issue resolution rate", estimatedValueImpact: "Responsible tech deployment with reduced ethical and legal risk" },
  { number: 97, category: "Technology & Data", processName: "Manage identity and access management (IAM) across systems", aiAgent: "IAM Agent", purpose: "Automate user provisioning, access reviews, and deprovisioning.", inputs: "HR system changes; role permission matrix; access request tickets; system audit logs", outputs: "Provisioned accounts; access review reports; deprovisioning confirmations; anomaly alerts", humanInTheLoop: "IT Security reviews access reviews and confirms deprovisioning", kpi: "Provisioning time; access review completion rate; orphaned account count", estimatedValueImpact: "Reduced identity-related security risk and admin overhead" },
  { number: 98, category: "Technology & Data", processName: "Monitor and respond to data breach and security incident events", aiAgent: "Incident Response Agent", purpose: "Detect, triage, and coordinate response to security incidents and data breaches.", inputs: "SIEM alerts; threat intelligence feeds; incident response playbooks; breach notification templates", outputs: "Incident triage report; response actions; breach notification drafts; post-incident review", humanInTheLoop: "CISO/IT Security lead manages incident response and regulatory notifications", kpi: "Detection time; containment time; breach notification compliance rate", estimatedValueImpact: "Faster containment and reduced regulatory and reputational exposure" },
  { number: 99, category: "Technology & Data", processName: "Conduct annual technology strategy and architecture review", aiAgent: "Architecture Review Agent", purpose: "Assess and evolve the technology architecture to support strategic goals.", inputs: "Current architecture diagrams; tech debt register; strategic plan; industry trends", outputs: "Architecture review report; tech debt prioritisation; target architecture roadmap", humanInTheLoop: "CTO/IT Director and executive team review and approve architecture direction", kpi: "Architecture review completion; tech debt reduction rate; architecture alignment score", estimatedValueImpact: "More strategic, scalable technology investment" },
  { number: 100, category: "Technology & Data", processName: "Automate digital experience testing and conversion rate optimisation", aiAgent: "CRO Agent", purpose: "Run A/B tests and heatmaps to continuously improve digital conversion rates.", inputs: "Website analytics; A/B test results; heatmap data; user journey recordings", outputs: "Test results summary; winning variant recommendations; implementation brief", humanInTheLoop: "Digital team reviews results and implements approved variants", kpi: "Conversion rate improvement; test velocity; uplift vs control", estimatedValueImpact: "Higher digital donation conversion and improved user experience" },
];

const tenantId = 1;

const strategyProfile = {
  mission: "Help nonprofit leaders make sharper strategic decisions with connected operational data, clearer priorities, and faster follow-through.",
  vision: "A mission-driven organisation where every team can see how daily execution contributes to measurable social impact.",
  purpose: "Turn planning, governance, delivery, and learning into one coherent operating system for sustainable nonprofit growth.",
};

const seededGoals = [
  {
    key: "goal-1",
    title: "Grow resilient unrestricted revenue",
    description: "Expand diversified fundraising so the organisation can fund strategic priorities with fewer concentration risks.",
    targetDate: "2026-12-31",
    status: "active",
    color: "#22c55e",
  },
  {
    key: "goal-2",
    title: "Improve programme outcomes visibility",
    description: "Standardise outcome tracking and executive reporting so leadership can act on impact data each quarter.",
    targetDate: "2026-10-31",
    status: "active",
    color: "#3b82f6",
  },
  {
    key: "goal-3",
    title: "Raise board and management operating cadence",
    description: "Shorten decision cycles by making strategy reviews, governance updates, and initiative progress visible in one place.",
    targetDate: "2026-09-30",
    status: "draft",
    color: "#f97316",
  },
];

const seededInitiatives = [
  {
    key: "initiative-1",
    initiativeId: "INIT-101",
    name: "Major Donor Pipeline Acceleration",
    goals: "Increase qualified major donor pipeline coverage and improve proposal velocity for top prospects.",
    achievement: "Targeting a 25% increase in pipeline value and better conversion tracking by year end.",
    startDate: "2026-04-01",
    endDate: "2026-11-30",
    linkedGoalKeys: ["goal-1"],
  },
  {
    key: "initiative-2",
    initiativeId: "INIT-102",
    name: "Quarterly Impact Scorecard Rollout",
    goals: "Launch a cross-functional scorecard covering programme reach, outcomes, and budget-to-impact efficiency.",
    achievement: "Executive team receives a standard quarterly scorecard with fewer manual reporting steps.",
    startDate: "2026-04-15",
    endDate: "2026-10-15",
    linkedGoalKeys: ["goal-2", "goal-3"],
  },
  {
    key: "initiative-3",
    initiativeId: "INIT-103",
    name: "Board Pack Automation and Governance Tracker",
    goals: "Reduce prep time for board and committee meetings while improving visibility into open decisions and actions.",
    achievement: "Board packs are assembled from live data and action closure is reviewed in every governance cycle.",
    startDate: "2026-05-01",
    endDate: "2026-09-30",
    linkedGoalKeys: ["goal-3"],
  },
];

async function seed() {
  console.log("Seeding local development data...");

  const existingTenants = await db.select().from(tenants).limit(100);
  const existingTenant = existingTenants.find((row) => row.id === tenantId);

  if (!existingTenant) {
    await db.insert(tenants).values({
      id: tenantId,
      name: "Default Tenant",
      slug: "default",
      status: "active",
      displayName: "Default Tenant",
      officialName: "Default Tenant",
      officialNationalId: "",
    });
    console.log("Seeded default tenant.");
  } else {
    console.log("Default tenant already exists, skipping.");
  }

  const existingProcesses = await db.select().from(processesTable).limit(1);
  if (existingProcesses.length === 0) {
    for (const p of processes) {
      await db.insert(processesTable).values({
        number: p.number,
        category: p.category,
        processDescription: p.processName,
        processName: "",
        aiAgent: p.aiAgent,
        purpose: p.purpose,
        inputs: p.inputs,
        outputs: p.outputs,
        humanInTheLoop: p.humanInTheLoop,
        kpi: p.kpi,
        estimatedValueImpact: p.estimatedValueImpact,
      });
    }
    console.log(`Seeded ${processes.length} processes.`);
  } else {
    console.log("Processes already seeded, skipping.");
  }

  const existingStrategy = await db
    .select()
    .from(tenantStrategyTable)
    .limit(100);

  const tenantStrategy = existingStrategy.find((row) => row.tenantId === tenantId);

  if (!tenantStrategy) {
    await db.insert(tenantStrategyTable).values({
      tenantId,
      ...strategyProfile,
    });
    console.log("Seeded tenant strategy profile.");
  } else {
    console.log("Tenant strategy profile already seeded, skipping.");
  }

  const goalIdsByKey = new Map<string, number>();

  for (let index = 0; index < seededGoals.length; index += 1) {
    const goal = seededGoals[index];
    const existingGoal = await db
      .select()
      .from(strategicGoalsTable)
      .limit(500);

    const matchingGoal = existingGoal.find(
      (row) => row.tenantId === tenantId && row.title === goal.title,
    );

    if (matchingGoal) {
      goalIdsByKey.set(goal.key, matchingGoal.id);
      continue;
    }

    const [createdGoal] = await db
      .insert(strategicGoalsTable)
      .values({
        tenantId,
        goalNumber: index + 1,
        title: goal.title,
        description: goal.description,
        targetDate: goal.targetDate,
        status: goal.status,
        color: goal.color,
      })
      .returning({ id: strategicGoalsTable.id });

    goalIdsByKey.set(goal.key, createdGoal.id);
  }

  console.log(`Ensured ${seededGoals.length} strategic goals.`);

  const initiativeIdsByKey = new Map<string, number>();

  for (const initiative of seededInitiatives) {
    const primaryGoalId = goalIdsByKey.get(initiative.linkedGoalKeys[0]) ?? null;
    const existingInitiative = await db
      .select()
      .from(initiatives)
      .limit(500);

    const matchingInitiative = existingInitiative.find(
      (row) => row.tenantId === tenantId && row.initiativeId === initiative.initiativeId,
    );

    if (matchingInitiative) {
      initiativeIdsByKey.set(initiative.key, matchingInitiative.id);
      continue;
    }

    const [createdInitiative] = await db
      .insert(initiatives)
      .values({
        tenantId,
        initiativeId: initiative.initiativeId,
        name: initiative.name,
        goals: initiative.goals,
        achievement: initiative.achievement,
        startDate: initiative.startDate,
        endDate: initiative.endDate,
        goalId: primaryGoalId,
      })
      .returning({ id: initiatives.id });

    initiativeIdsByKey.set(initiative.key, createdInitiative.id);
  }

  console.log(`Ensured ${seededInitiatives.length} initiatives.`);

  let linkedCount = 0;
  for (const initiative of seededInitiatives) {
    const initiativeDbId = initiativeIdsByKey.get(initiative.key);
    if (!initiativeDbId) continue;

    for (const goalKey of initiative.linkedGoalKeys) {
      const goalDbId = goalIdsByKey.get(goalKey);
      if (!goalDbId) continue;

      const existingLink = await db
        .select()
        .from(strategicGoalInitiativesTable)
        .limit(100);

      const alreadyLinked = existingLink.some(
        (row) => row.goalId === goalDbId && row.initiativeId === initiativeDbId,
      );
      if (alreadyLinked) continue;

      await db.insert(strategicGoalInitiativesTable).values({
        goalId: goalDbId,
        initiativeId: initiativeDbId,
      });
      linkedCount += 1;
    }
  }

  console.log(`Ensured ${linkedCount} new goal-to-initiative links.`);
  process.exit(0);
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
